const VOCAB = [
  // --- BATCH 1 (Original 130 words) ---
  {es:"el/la", en:"the", cat:"Gramática", ex:"__el__ libro está aquí — the book is here"},
  {es:"de", en:"of / from", cat:"Gramática", ex:"soy __de__ España — I am from Spain"},
  {es:"que", en:"that / which", cat:"Gramática", ex:"creo __que__ sí — I think that yes"},
  {es:"y", en:"and", cat:"Gramática", ex:"tú __y__ yo — you and I"},
  {es:"a", en:"to / at", cat:"Gramática", ex:"voy __a__ casa — I'm going home"},
  {es:"en", en:"in / on", cat:"Gramática", ex:"está __en__ la mesa — it's on the table"},
  {es:"un/una", en:"a / an", cat:"Gramática", ex:"quiero __un__ café — I want a coffee"},
  {es:"ser", en:"to be (permanent)", cat:"Verbos", ex:"yo __soy__ alto — I am tall"},
  {es:"se", en:"oneself / (reflexive)", cat:"Gramática", ex:"__se__ llama Ana — her name is Ana"},
  {es:"no", en:"no / not", cat:"Gramática", ex:"__no__ lo sé — I don't know"},
  {es:"haber", en:"to have (aux) / there is", cat:"Verbos", ex:"__hay__ dos gatos — there are two cats"},
  {es:"por", en:"for / because of", cat:"Gramática", ex:"gracias __por__ todo — thanks for everything"},
  {es:"con", en:"with", cat:"Gramática", ex:"voy __con__ ella — I'm going with her"},
  {es:"su", en:"his / her / your", cat:"Gramática", ex:"es __su__ casa — it's her house"},
  {es:"para", en:"for / in order to", cat:"Gramática", ex:"esto es __para__ ti — this is for you"},
  {es:"como", en:"like / as / how", cat:"Gramática", ex:"¿__cómo__ estás? — how are you?"},
  {es:"estar", en:"to be (state/location)", cat:"Verbos", ex:"__estoy__ bien — I am fine"},
  {es:"tener", en:"to have", cat:"Verbos", ex:"__tengo__ hambre — I am hungry"},
  {es:"le", en:"to him/her (indirect)", cat:"Gramática", ex:"__le__ di el libro — I gave him the book"},
  {es:"lo", en:"it / him", cat:"Gramática", ex:"no __lo__ entiendo — I don't understand it"},
  {es:"todo", en:"all / everything", cat:"Gramática", ex:"__todo__ está bien — everything is fine"},
  {es:"pero", en:"but", cat:"Gramática", ex:"quiero ir __pero__ no puedo — I want to go but I can't"},
  {es:"más", en:"more", cat:"Gramática", ex:"quiero __más__ agua — I want more water"},
  {es:"hacer", en:"to do / make", cat:"Verbos", ex:"¿qué __haces__? — what are you doing?"},
  {es:"o", en:"or", cat:"Gramática", ex:"té __o__ café — tea or coffee"},
  {es:"poder", en:"to be able to / can", cat:"Verbos", ex:"__puedo__ ayudarte — I can help you"},
  {es:"decir", en:"to say / tell", cat:"Verbos", ex:"¿qué __dices__? — what do you say?"},
  {es:"este/esta", en:"this", cat:"Gramática", ex:"__este__ libro es bueno — this book is good"},
  {es:"ir", en:"to go", cat:"Verbos", ex:"__voy__ a la tienda — I'm going to the store"},
  {es:"otro", en:"other / another", cat:"Gramática", ex:"dame __otro__ ejemplo — give me another example"},
  {es:"ese/esa", en:"that", cat:"Gramática", ex:"__esa__ casa es grande — that house is big"},
  {es:"la", en:"her / it (fem.)", cat:"Gramática", ex:"__la__ veo mañana — I'll see her tomorrow"},
  {es:"si", en:"if", cat:"Gramática", ex:"__si__ quieres, vamos — if you want, let's go"},
  {es:"me", en:"me / myself", cat:"Gramática", ex:"__me__ gusta el café — I like coffee"},
  {es:"ya", en:"already / now", cat:"Gramática", ex:"__ya__ terminé — I already finished"},
  {es:"vez", en:"time / occasion", cat:"Sustantivos", ex:"una __vez__ más — one more time"},
  {es:"muy", en:"very", cat:"Gramática", ex:"estoy __muy__ cansado — I am very tired"},
  {es:"año", en:"year", cat:"Sustantivos", ex:"este __año__ viajo — this year I'm traveling"},
  {es:"dar", en:"to give", cat:"Verbos", ex:"¿me __das__ agua? — will you give me water?"},
  {es:"cuando", en:"when", cat:"Gramática", ex:"__cuando__ llegues, llámame — when you arrive, call me"},
  {es:"él/ella", en:"he / she", cat:"Gramática", ex:"__él__ es mi amigo — he is my friend"},
  {es:"mi/mis", en:"my", cat:"Gramática", ex:"esta es __mi__ familia — this is my family"},
  {es:"antes", en:"before", cat:"Tiempo", ex:"llegué __antes__ que tú — I arrived before you"},
  {es:"bien", en:"well / good", cat:"Gramática", ex:"todo salió __bien__ — everything went well"},
  {es:"nosotros/nosotras", en:"we / us", cat:"Gramática", ex:"__nosotros__ vamos juntos — we're going together"},
  {es:"querer", en:"to want / love", cat:"Verbos", ex:"te __quiero__ — I love you"},
  {es:"así", en:"like this / so", cat:"Gramática", ex:"hazlo __así__ — do it like this"},
  {es:"nuestro", en:"our", cat:"Gramática", ex:"es __nuestro__ hogar — it's our home"},
  {es:"tanto", en:"so much", cat:"Gramática", ex:"te quiero __tanto__ — I love you so much"},
  {es:"hombre", en:"man", cat:"Sustantivos", ex:"el __hombre__ camina — the man walks"},
  {es:"parecer", en:"to seem", cat:"Verbos", ex:"__parece__ interesante — it seems interesting"},
  {es:"nada", en:"nothing", cat:"Gramática", ex:"no quiero __nada__ — I don't want anything"},
  {es:"mujer", en:"woman", cat:"Sustantivos", ex:"la __mujer__ trabaja — the woman works"},
  {es:"tiempo", en:"time / weather", cat:"Sustantivos", ex:"no tengo __tiempo__ — I don't have time"},
  {es:"mismo", en:"same", cat:"Gramática", ex:"es lo __mismo__ — it's the same"},
  {es:"ahora", en:"now", cat:"Tiempo", ex:"vengo __ahora__ — I'm coming now"},
  {es:"algo", en:"something", cat:"Gramática", ex:"quiero decirte __algo__ — I want to tell you something"},
  {es:"nunca", en:"never", cat:"Tiempo", ex:"__nunca__ he estado allí — I've never been there"},
  {es:"día", en:"day", cat:"Sustantivos", ex:"buen __día__ — good day"},
  {es:"casa", en:"house / home", cat:"Sustantivos", ex:"voy a __casa__ — I'm going home"},
  {es:"vida", en:"life", cat:"Sustantivos", ex:"me encanta la __vida__ — I love life"},
  {es:"saber", en:"to know (facts)", cat:"Verbos", ex:"no __sé__ — I don't know"},
  {es:"donde", en:"where", cat:"Gramática", ex:"¿__dónde__ estás? — where are you?"},
  {es:"gente", en:"people", cat:"Sustantivos", ex:"hay mucha __gente__ — there are many people"},
  {es:"trabajo", en:"work / job", cat:"Sustantivos", ex:"voy al __trabajo__ — I'm going to work"},
  {es:"hasta", en:"until", cat:"Gramática", ex:"__hasta__ mañana — see you tomorrow"},
  {es:"palabra", en:"word", cat:"Sustantivos", ex:"esa __palabra__ es nueva — that word is new"},
  {es:"ver", en:"to see", cat:"Verbos", ex:"quiero __verte__ — I want to see you"},
  {es:"quien", en:"who", cat:"Gramática", ex:"¿__quién__ es? — who is it?"},
  {es:"llegar", en:"to arrive", cat:"Verbos", ex:"acabo de __llegar__ — I just arrived"},
  {es:"pasar", en:"to pass / happen", cat:"Verbos", ex:"¿qué __pasa__? — what's happening?"},
  {es:"tiempo libre", en:"free time", cat:"Frases", ex:"no tengo __tiempo libre__ — I have no free time"},
  {es:"gracias", en:"thank you", cat:"Frases", ex:"muchas __gracias__ — thank you very much"},
  {es:"por favor", en:"please", cat:"Frases", ex:"ayúdame, __por favor__ — help me, please"},
  {es:"buenos días", en:"good morning", cat:"Frases", ex:"__buenos días__, señora — good morning, ma'am"},
  {es:"buenas noches", en:"good night", cat:"Frases", ex:"__buenas noches__, hasta mañana — good night, see you tomorrow"},
  {es:"de nada", en:"you're welcome", cat:"Frases", ex:"—gracias —__de nada__ — thanks / you're welcome"},
  {es:"lo siento", en:"I'm sorry", cat:"Frases", ex:"__lo siento__ mucho — I'm very sorry"},
  {es:"¿cómo te llamas?", en:"what's your name?", cat:"Frases", ex:"__¿cómo te llamas?__ — what's your name?"},
  {es:"mucho gusto", en:"nice to meet you", cat:"Frases", ex:"__mucho gusto__, soy Ana — nice to meet you, I'm Ana"},
  {es:"no entiendo", en:"I don't understand", cat:"Frases", ex:"__no entiendo__, repite por favor — I don't understand, repeat please"},
  {es:"¿cuánto cuesta?", en:"how much does it cost?", cat:"Frases", ex:"__¿cuánto cuesta?__ esto — how much does this cost?"},
  {es:"quisiera", en:"I would like", cat:"Frases", ex:"__quisiera__ un café — I would like a coffee"},
  {es:"¿dónde está?", en:"where is it?", cat:"Frases", ex:"__¿dónde está__ el baño? — where is the bathroom?"},
  {es:"tengo que", en:"I have to", cat:"Frases", ex:"__tengo que__ irme — I have to go"},
  {es:"me gustaría", en:"I would like", cat:"Frases", ex:"__me gustaría__ ir contigo — I would like to go with you"},
  {es:"no pasa nada", en:"it's okay / no worries", cat:"Frases", ex:"__no pasa nada__, tranquilo — it's fine, don't worry"},
  {es:"amigo/amiga", en:"friend", cat:"Sustantivos", ex:"es mi __amigo__ — he's my friend"},
  {es:"familia", en:"family", cat:"Sustantivos", ex:"amo a mi __familia__ — I love my family"},
  {es:"comida", en:"food", cat:"Sustantivos", ex:"la __comida__ está lista — the food is ready"},
  {es:"agua", en:"water", cat:"Sustantivos", ex:"necesito __agua__ — I need water"},
  {es:"dinero", en:"money", cat:"Sustantivos", ex:"no tengo __dinero__ — I don't have money"},
  {es:"ciudad", en:"city", cat:"Sustantivos", ex:"vivo en la __ciudad__ — I live in the city"},
  {es:"escuela", en:"school", cat:"Sustantivos", ex:"voy a la __escuela__ — I'm going to school"},
  {es:"libro", en:"book", cat:"Sustantivos", ex:"leo un __libro__ — I'm reading a book"},
  {es:"noche", en:"night", cat:"Sustantivos", ex:"salimos por la __noche__ — we go out at night"},
  {es:"mañana", en:"morning / tomorrow", cat:"Tiempo", ex:"nos vemos __mañana__ — see you tomorrow"},
  {es:"hoy", en:"today", cat:"Tiempo", ex:"__hoy__ es lunes — today is Monday"},
  {es:"semana", en:"week", cat:"Tiempo", ex:"esta __semana__ estoy ocupado — this week I'm busy"},
  {es:"siempre", en:"always", cat:"Tiempo", ex:"__siempre__ llego temprano — I always arrive early"},
  {es:"todavía", en:"still / yet", cat:"Tiempo", ex:"__todavía__ no llega — he still hasn't arrived"},
  {es:"pronto", en:"soon", cat:"Tiempo", ex:"vuelvo __pronto__ — I'll be back soon"},
  {es:"despues", en:"after / later", cat:"Tiempo", ex:"nos vemos __después__ — see you later"},
  {es:"bueno/buena", en:"good", cat:"Adjetivos", ex:"es una __buena__ idea — it's a good idea"},
  {es:"malo/mala", en:"bad", cat:"Adjetivos", ex:"no es __malo__ — it's not bad"},
  {es:"grande", en:"big", cat:"Adjetivos", ex:"una casa __grande__ — a big house"},
  {es:"pequeño/pequeña", en:"small", cat:"Adjetivos", ex:"un perro __pequeño__ — a small dog"},
  {es:"nuevo/nueva", en:"new", cat:"Adjetivos", ex:"tengo un teléfono __nuevo__ — I have a new phone"},
  {es:"feliz", en:"happy", cat:"Adjetivos", ex:"estoy muy __feliz__ — I am very happy"},
  {es:"difícil", en:"difficult", cat:"Adjetivos", ex:"es __difícil__ de explicar — it's difficult to explain"},
  {es:"fácil", en:"easy", cat:"Adjetivos", ex:"eso es __fácil__ — that's easy"},
  {es:"importante", en:"important", cat:"Adjetivos", ex:"es muy __importante__ — it's very important"},
  {es:"cansado/cansada", en:"tired", cat:"Adjetivos", ex:"estoy __cansado__ hoy — I'm tired today"},
  {es:"comer", en:"to eat", cat:"Verbos", ex:"vamos a __comer__ — let's go eat"},
  {es:"beber", en:"to drink", cat:"Verbos", ex:"quiero __beber__ agua — I want to drink water"},
  {es:"dormir", en:"to sleep", cat:"Verbos", ex:"necesito __dormir__ — I need to sleep"},
  {es:"trabajar", en:"to work", cat:"Verbos", ex:"__trabajo__ todos los días — I work every day"},
  {es:"vivir", en:"to live", cat:"Verbos", ex:"__vivo__ en Madrid — I live in Madrid"},
  {es:"hablar", en:"to speak", cat:"Verbos", ex:"__hablo__ español — I speak Spanish"},
  {es:"escuchar", en:"to listen", cat:"Verbos", ex:"me gusta __escuchar__ música — I like listening to music"},
  {es:"entender", en:"to understand", cat:"Verbos", ex:"ahora __entiendo__ — now I understand"},
  {es:"buscar", en:"to look for", cat:"Verbos", ex:"__busco__ trabajo — I'm looking for a job"},
  {es:"encontrar", en:"to find", cat:"Verbos", ex:"no puedo __encontrar__ mis llaves — I can't find my keys"},
  {es:"empezar", en:"to start", cat:"Verbos", ex:"vamos a __empezar__ — let's start"},
  {es:"terminar", en:"to finish", cat:"Verbos", ex:"ya __terminé__ — I already finished"},
  {es:"ayudar", en:"to help", cat:"Verbos", ex:"¿puedes __ayudarme__? — can you help me?"},
  {es:"pensar", en:"to think", cat:"Verbos", ex:"lo voy a __pensar__ — I'll think about it"},
  {es:"sentir", en:"to feel", cat:"Verbos", ex:"__siento__ que sí — I feel like yes"},
  {es:"uno", en:"one", cat:"Números", ex:"tengo __uno__ solo — I only have one"},
  {es:"dos", en:"two", cat:"Números", ex:"somos __dos__ — we are two"},
  {es:"tres", en:"three", cat:"Números", ex:"__tres__ hermanos — three siblings"},
  {es:"cinco", en:"five", cat:"Números", ex:"son las __cinco__ — it's five o'clock"},
  {es:"diez", en:"ten", cat:"Números", ex:"cuesta __diez__ euros — it costs ten euros"},
  
  // --- BATCH 2 (200 New words, Spain Spanish focused) ---
  {es:"vosotros/vosotras", en:"you all (informal)", cat:"Gramática", ex:"¿__vosotros__ de dónde sois? — where are you all from?"},
  {es:"vuestro/vuestra", en:"your (plural informal)", cat:"Gramática", ex:"me gusta __vuestro__ coche — I like your car"},
  {es:"vale", en:"okay / alright", cat:"Frases", ex:"nos vemos a las ocho, ¿__vale__? — see you at eight, okay?"},
  {es:"tío/tía", en:"guy / dude / uncle / aunt", cat:"Sustantivos", ex:"¿qué pasa, __tío__? — what's up, dude?"},
  {es:"chaval/chavala", en:"kid / young person", cat:"Sustantivos", ex:"ese __chaval__ juega muy bien — that kid plays very well"},
  {es:"molar", en:"to be cool / to like", cat:"Verbos", ex:"me __mola__ mucho esta canción — I really like this song"},
  {es:"guay", en:"cool / great", cat:"Adjetivos", ex:"es una película muy __guay__ — it's a very cool movie"},
  {es:"coche", en:"car", cat:"Sustantivos", ex:"tengo el __coche__ en el taller — I have the car in the shop"},
  {es:"ordenador", en:"computer", cat:"Sustantivos", ex:"trabajo con el __ordenador__ — I work with the computer"},
  {es:"zumo", en:"juice", cat:"Sustantivos", ex:"quiero un __zumo__ de naranja — I want an orange juice"},
  {es:"patata", en:"potato", cat:"Sustantivos", ex:"una tortilla de __patatas__ — a potato omelette"},
  {es:"gafas", en:"glasses", cat:"Sustantivos", ex:"no veo sin mis __gafas__ — I can't see without my glasses"},
  {es:"piso", en:"apartment / floor", cat:"Sustantivos", ex:"alquilo un __piso__ en el centro — I rent an apartment downtown"},
  {es:"móvil", en:"mobile phone", cat:"Sustantivos", ex:"me he dejado el __móvil__ — I left my phone"},
  {es:"luego", en:"later", cat:"Tiempo", ex:"hasta __luego__ — see you later"},
  {es:"venga", en:"come on / alright", cat:"Frases", ex:"__venga__, vamos ya — come on, let's go already"},
  {es:"joder", en:"fuck / damn (common filler)", cat:"Exclamaciones", ex:"¡__joder__, qué calor hace! — damn, it's hot!"},
  {es:"hostia", en:"holy crap / damn", cat:"Exclamaciones", ex:"¡la __hostia__! — holy crap!"},
  {es:"pasta", en:"money / cash (slang)", cat:"Sustantivos", ex:"eso cuesta mucha __pasta__ — that costs a lot of money"},
  {es:"curro", en:"job / work (slang)", cat:"Sustantivos", ex:"tengo mucho __curro__ hoy — I have a lot of work today"},
  {es:"currar", en:"to work (slang)", cat:"Verbos", ex:"tengo que __currar__ mañana — I have to work tomorrow"},
  {es:"guiri", en:"foreign tourist (slang)", cat:"Sustantivos", ex:"está lleno de __guiris__ — it's full of tourists"},
  {es:"caña", en:"small draft beer", cat:"Sustantivos", ex:"vamos a tomar unas __cañas__ — let's go have some beers"},
  {es:"tapas", en:"snacks with drinks", cat:"Sustantivos", ex:"pedimos unas __tapas__ — let's order some tapas"},
  {es:"bar", en:"bar / café", cat:"Sustantivos", ex:"quedamos en el __bar__ — let's meet at the bar"},
  {es:"calle", en:"street", cat:"Sustantivos", ex:"vivo en esta __calle__ — I live on this street"},
  {es:"plaza", en:"square", cat:"Sustantivos", ex:"la __plaza__ mayor — the main square"},
  {es:"metro", en:"subway", cat:"Sustantivos", ex:"voy en __metro__ al trabajo — I take the subway to work"},
  {es:"autobús", en:"bus", cat:"Sustantivos", ex:"el __autobús__ llega tarde — the bus is late"},
  {es:"billete", en:"ticket / banknote", cat:"Sustantivos", ex:"un __billete__ de ida y vuelta — a round-trip ticket"},
  {es:"estación", en:"station / season", cat:"Sustantivos", ex:"la __estación__ de tren — the train station"},
  {es:"aeropuerto", en:"airport", cat:"Sustantivos", ex:"vamos al __aeropuerto__ — we're going to the airport"},
  {es:"viaje", en:"trip / journey", cat:"Sustantivos", ex:"¡buen __viaje__! — have a good trip!"},
  {es:"vacaciones", en:"holidays / vacation", cat:"Sustantivos", ex:"necesito unas __vacaciones__ — I need a vacation"},
  {es:"playa", en:"beach", cat:"Sustantivos", ex:"vamos a la __playa__ — let's go to the beach"},
  {es:"montaña", en:"mountain", cat:"Sustantivos", ex:"me gusta la __montaña__ — I like the mountains"},
  {es:"pueblo", en:"village / town / people", cat:"Sustantivos", ex:"es un __pueblo__ muy bonito — it's a very pretty village"},
  {es:"país", en:"country", cat:"Sustantivos", ex:"España es un gran __país__ — Spain is a great country"},
  {es:"mundo", en:"world", cat:"Sustantivos", ex:"viajar por el __mundo__ — to travel the world"},
  {es:"lugar", en:"place", cat:"Sustantivos", ex:"este __lugar__ es genial — this place is great"},
  {es:"sitio", en:"place / spot", cat:"Sustantivos", ex:"guárdame el __sitio__ — save my spot"},
  {es:"aquí", en:"here", cat:"Gramática", ex:"ven __aquí__ — come here"},
  {es:"ahí", en:"there", cat:"Gramática", ex:"ponlo __ahí__ — put it there"},
  {es:"allí", en:"over there", cat:"Gramática", ex:"él está __allí__ — he is over there"},
  {es:"cerca", en:"close / near", cat:"Gramática", ex:"está muy __cerca__ — it's very close"},
  {es:"lejos", en:"far", cat:"Gramática", ex:"vivo muy __lejos__ — I live very far"},
  {es:"arriba", en:"up / above", cat:"Gramática", ex:"mira hacia __arriba__ — look up"},
  {es:"abajo", en:"down / below", cat:"Gramática", ex:"vamos para __abajo__ — let's go down"},
  {es:"dentro", en:"inside", cat:"Gramática", ex:"está __dentro__ de la caja — it's inside the box"},
  {es:"fuera", en:"outside", cat:"Gramática", ex:"hace frío __fuera__ — it's cold outside"},
  {es:"delante", en:"in front", cat:"Gramática", ex:"está __delante__ de ti — it's in front of you"},
  {es:"detrás", en:"behind", cat:"Gramática", ex:"mira __detrás__ de la puerta — look behind the door"},
  {es:"derecha", en:"right (direction)", cat:"Gramática", ex:"gira a la __derecha__ — turn right"},
  {es:"izquierda", en:"left (direction)", cat:"Gramática", ex:"gira a la __izquierda__ — turn left"},
  {es:"centro", en:"center / downtown", cat:"Sustantivos", ex:"vamos al __centro__ comercial — let's go to the mall"},
  {es:"lado", en:"side", cat:"Sustantivos", ex:"al otro __lado__ — on the other side"},
  {es:"medio", en:"middle / half", cat:"Sustantivos", ex:"en __medio__ de la calle — in the middle of the street"},
  {es:"principio", en:"beginning", cat:"Sustantivos", ex:"desde el __principio__ — from the beginning"},
  {es:"final", en:"end", cat:"Sustantivos", ex:"al __final__ de la peli — at the end of the movie"},
  {es:"hora", en:"hour / time", cat:"Tiempo", ex:"¿qué __hora__ es? — what time is it?"},
  {es:"minuto", en:"minute", cat:"Tiempo", ex:"espera un __minuto__ — wait a minute"},
  {es:"segundo", en:"second", cat:"Tiempo", ex:"un __segundo__, por favor — one second, please"},
  {es:"mes", en:"month", cat:"Tiempo", ex:"el próximo __mes__ — next month"},
  {es:"siglo", en:"century", cat:"Tiempo", ex:"en el __siglo__ veintiuno — in the twenty-first century"},
  {es:"lunes", en:"Monday", cat:"Tiempo", ex:"nos vemos el __lunes__ — see you on Monday"},
  {es:"martes", en:"Tuesday", cat:"Tiempo", ex:"el __martes__ no puedo — I can't on Tuesday"},
  {es:"miércoles", en:"Wednesday", cat:"Tiempo", ex:"hoy es __miércoles__ — today is Wednesday"},
  {es:"jueves", en:"Thursday", cat:"Tiempo", ex:"el __jueves__ trabajo — I work on Thursday"},
  {es:"viernes", en:"Friday", cat:"Tiempo", ex:"¡por fin es __viernes__! — finally it's Friday!"},
  {es:"sábado", en:"Saturday", cat:"Tiempo", ex:"el __sábado__ salimos — we go out on Saturday"},
  {es:"domingo", en:"Sunday", cat:"Tiempo", ex:"el __domingo__ descanso — I rest on Sunday"},
  {es:"enero", en:"January", cat:"Tiempo", ex:"hace frío en __enero__ — it's cold in January"},
  {es:"verano", en:"summer", cat:"Tiempo", ex:"odio el calor de __verano__ — I hate the summer heat"},
  {es:"invierno", en:"winter", cat:"Tiempo", ex:"en __invierno__ nieva — it snows in winter"},
  {es:"primavera", en:"spring", cat:"Tiempo", ex:"la __primavera__ es bonita — spring is pretty"},
  {es:"otoño", en:"autumn / fall", cat:"Tiempo", ex:"las hojas caen en __otoño__ — leaves fall in autumn"},
  {es:"mañana (noun)", en:"morning", cat:"Tiempo", ex:"trabajo por la __mañana__ — I work in the morning"},
  {es:"tarde", en:"afternoon / late", cat:"Tiempo", ex:"es muy __tarde__ — it's very late"},
  {es:"temprano", en:"early", cat:"Tiempo", ex:"me levanto __temprano__ — I wake up early"},
  {es:"ayer", en:"yesterday", cat:"Tiempo", ex:"__ayer__ llovió — it rained yesterday"},
  {es:"anteayer", en:"day before yesterday", cat:"Tiempo", ex:"lo compré __anteayer__ — I bought it the day before yesterday"},
  {es:"pasado mañana", en:"day after tomorrow", cat:"Tiempo", ex:"llego __pasado mañana__ — I arrive the day after tomorrow"},
  {es:"mientras", en:"while", cat:"Tiempo", ex:"lee __mientras__ comes — read while you eat"},
  {es:"durante", en:"during", cat:"Tiempo", ex:"__durante__ la clase — during the class"},
  {es:"jamás", en:"never", cat:"Tiempo", ex:"__jamás__ haré eso — I will never do that"},
  {es:"enseguida", en:"right away", cat:"Tiempo", ex:"voy __enseguida__ — I'm coming right away"},
  {es:"siempre", en:"always", cat:"Tiempo", ex:"__siempre__ te amaré — I will always love you"},
  {es:"nunca", en:"never", cat:"Tiempo", ex:"__nunca__ digas nunca — never say never"},
  {es:"a veces", en:"sometimes", cat:"Tiempo", ex:"__a veces__ dudo — sometimes I doubt"},
  {es:"niño/niña", en:"child / boy / girl", cat:"Sustantivos", ex:"el __niño__ juega — the boy plays"},
  {es:"chico/chica", en:"boy / girl / guy", cat:"Sustantivos", ex:"es un __chico__ listo — he's a smart guy"},
  {es:"padre", en:"father", cat:"Sustantivos", ex:"mi __padre__ se llama Juan — my father is named Juan"},
  {es:"madre", en:"mother", cat:"Sustantivos", ex:"amo a mi __madre__ — I love my mother"},
  {es:"hermano/hermana", en:"brother / sister", cat:"Sustantivos", ex:"tengo una __hermana__ — I have a sister"},
  {es:"hijo/hija", en:"son / daughter", cat:"Sustantivos", ex:"su __hijo__ es alto — his son is tall"},
  {es:"abuelo/abuela", en:"grandfather / grandmother", cat:"Sustantivos", ex:"mi __abuelo__ tiene ochenta años — my grandfather is eighty"},
  {es:"tío/tía (family)", en:"uncle / aunt", cat:"Sustantivos", ex:"mi __tía__ vive en Madrid — my aunt lives in Madrid"},
  {es:"primo/prima", en:"cousin", cat:"Sustantivos", ex:"juego con mi __primo__ — I play with my cousin"},
  {es:"esposo/esposa", en:"husband / wife", cat:"Sustantivos", ex:"mi __esposo__ trabaja aquí — my husband works here"},
  {es:"marido", en:"husband", cat:"Sustantivos", ex:"su __marido__ es médico — her husband is a doctor"},
  {es:"mujer (wife)", en:"wife / woman", cat:"Sustantivos", ex:"su __mujer__ es abogada — his wife is a lawyer"},
  {es:"novio/novia", en:"boyfriend / girlfriend / groom / bride", cat:"Sustantivos", ex:"tiene __novio__ nuevo — she has a new boyfriend"},
  {es:"pareja", en:"partner / couple", cat:"Sustantivos", ex:"somos una buena __pareja__ — we are a good couple"},
  {es:"señor", en:"sir / mister / man", cat:"Sustantivos", ex:"el __señor__ García — Mr. Garcia"},
  {es:"señora", en:"ma'am / mrs / woman", cat:"Sustantivos", ex:"la __señora__ López — Mrs. Lopez"},
  {es:"jefe/jefa", en:"boss", cat:"Sustantivos", ex:"mi __jefe__ es muy estricto — my boss is very strict"},
  {es:"compañero/compañera", en:"companion / classmate / coworker", cat:"Sustantivos", ex:"es mi __compañero__ de trabajo — he's my coworker"},
  {es:"perro", en:"dog", cat:"Sustantivos", ex:"el __perro__ ladra — the dog barks"},
  {es:"gato", en:"cat", cat:"Sustantivos", ex:"tengo un __gato__ negro — I have a black cat"},
  {es:"pájaro", en:"bird", cat:"Sustantivos", ex:"el __pájaro__ canta — the bird sings"},
  {es:"caballo", en:"horse", cat:"Sustantivos", ex:"monto a __caballo__ — I ride a horse"},
  {es:"cabeza", en:"head", cat:"Sustantivos", ex:"me duele la __cabeza__ — my head hurts"},
  {es:"cara", en:"face", cat:"Sustantivos", ex:"lávate la __cara__ — wash your face"},
  {es:"ojo", en:"eye", cat:"Sustantivos", ex:"tiene los __ojos__ azules — he has blue eyes"},
  {es:"boca", en:"mouth", cat:"Sustantivos", ex:"cierra la __boca__ — close your mouth"},
  {es:"mano", en:"hand", cat:"Sustantivos", ex:"dame la __mano__ — give me your hand"},
  {es:"brazo", en:"arm", cat:"Sustantivos", ex:"me rompí el __brazo__ — I broke my arm"},
  {es:"pie", en:"foot", cat:"Sustantivos", ex:"me duele el __pie__ — my foot hurts"},
  {es:"pierna", en:"leg", cat:"Sustantivos", ex:"tengo las __piernas__ cansadas — my legs are tired"},
  {es:"cuerpo", en:"body", cat:"Sustantivos", ex:"el __cuerpo__ humano — the human body"},
  {es:"espalda", en:"back", cat:"Sustantivos", ex:"me duele la __espalda__ — my back hurts"},
  {es:"corazón", en:"heart", cat:"Sustantivos", ex:"te quiero con todo mi __corazón__ — I love you with all my heart"},
  {es:"ropa", en:"clothes", cat:"Sustantivos", ex:"tengo __ropa__ nueva — I have new clothes"},
  {es:"camiseta", en:"t-shirt", cat:"Sustantivos", ex:"una __camiseta__ blanca — a white t-shirt"},
  {es:"pantalones", en:"pants / trousers", cat:"Sustantivos", ex:"unos __pantalones__ vaqueros — some jeans"},
  {es:"zapatos", en:"shoes", cat:"Sustantivos", ex:"cómprate esos __zapatos__ — buy those shoes"},
  {es:"abrigo", en:"coat", cat:"Sustantivos", ex:"ponte el __abrigo__ — put on your coat"},
  {es:"vestido", en:"dress", cat:"Sustantivos", ex:"llevaba un __vestido__ rojo — she wore a red dress"},
  {es:"desayuno", en:"breakfast", cat:"Sustantivos", ex:"el __desayuno__ está listo — breakfast is ready"},
  {es:"almuerzo", en:"lunch", cat:"Sustantivos", ex:"¿qué hay para el __almuerzo__? — what's for lunch?"},
  {es:"cena", en:"dinner", cat:"Sustantivos", ex:"te invito a la __cena__ — I invite you to dinner"},
  {es:"pan", en:"bread", cat:"Sustantivos", ex:"un bocadillo de __pan__ — a bread sandwich"},
  {es:"queso", en:"cheese", cat:"Sustantivos", ex:"un poco de __queso__ — a bit of cheese"},
  {es:"carne", en:"meat", cat:"Sustantivos", ex:"no como __carne__ — I don't eat meat"},
  {es:"pescado", en:"fish (food)", cat:"Sustantivos", ex:"hoy cenamos __pescado__ — today we dine fish"},
  {es:"pollo", en:"chicken", cat:"Sustantivos", ex:"arroz con __pollo__ — rice with chicken"},
  {es:"leche", en:"milk", cat:"Sustantivos", ex:"café con __leche__ — coffee with milk"},
  {es:"café", en:"coffee", cat:"Sustantivos", ex:"necesito un __café__ — I need a coffee"},
  {es:"té", en:"tea", cat:"Sustantivos", ex:"prefiero el __té__ — I prefer tea"},
  {es:"vino", en:"wine", cat:"Sustantivos", ex:"una copa de __vino__ — a glass of wine"},
  {es:"cerveza", en:"beer", cat:"Sustantivos", ex:"una __cerveza__ fría — a cold beer"},
  {es:"sal", en:"salt", cat:"Sustantivos", ex:"pásame la __sal__ — pass me the salt"},
  {es:"azúcar", en:"sugar", cat:"Sustantivos", ex:"un poco de __azúcar__ — a bit of sugar"},
  {es:"fruta", en:"fruit", cat:"Sustantivos", ex:"come más __fruta__ — eat more fruit"},
  {es:"manzana", en:"apple", cat:"Sustantivos", ex:"una __manzana__ verde — a green apple"},
  {es:"naranja", en:"orange", cat:"Sustantivos", ex:"el color __naranja__ — the color orange"},
  {es:"cama", en:"bed", cat:"Sustantivos", ex:"voy a la __cama__ — I'm going to bed"},
  {es:"mesa", en:"table", cat:"Sustantivos", ex:"pon la __mesa__ — set the table"},
  {es:"silla", en:"chair", cat:"Sustantivos", ex:"siéntate en esta __silla__ — sit in this chair"},
  {es:"puerta", en:"door", cat:"Sustantivos", ex:"abre la __puerta__ — open the door"},
  {es:"ventana", en:"window", cat:"Sustantivos", ex:"cierra la __ventana__ — close the window"},
  {es:"pared", en:"wall", cat:"Sustantivos", ex:"la __pared__ es blanca — the wall is white"},
  {es:"suelo", en:"floor / ground", cat:"Sustantivos", ex:"se cayó al __suelo__ — it fell to the floor"},
  {es:"techo", en:"roof / ceiling", cat:"Sustantivos", ex:"mira al __techo__ — look at the ceiling"},
  {es:"baño", en:"bathroom", cat:"Sustantivos", ex:"¿dónde está el __baño__? — where is the bathroom?"},
  {es:"habitación", en:"room", cat:"Sustantivos", ex:"mi __habitación__ es grande — my room is big"},
  {es:"llave", en:"key", cat:"Sustantivos", ex:"he perdido las __llaves__ — I lost the keys"},
  {es:"luz", en:"light", cat:"Sustantivos", ex:"apaga la __luz__ — turn off the light"},
  {es:"sol", en:"sun", cat:"Sustantivos", ex:"hace mucho __sol__ — it's very sunny"},
  {es:"luna", en:"moon", cat:"Sustantivos", ex:"la __luna__ llena — the full moon"},
  {es:"estrella", en:"star", cat:"Sustantivos", ex:"mira esa __estrella__ — look at that star"},
  {es:"cielo", en:"sky / heaven", cat:"Sustantivos", ex:"el __cielo__ es azul — the sky is blue"},
  {es:"tierra", en:"earth / land / dirt", cat:"Sustantivos", ex:"el planeta __tierra__ — planet earth"},
  {es:"mar", en:"sea", cat:"Sustantivos", ex:"el __mar__ está en calma — the sea is calm"},
  {es:"río", en:"river", cat:"Sustantivos", ex:"el __río__ Tajo — the Tagus river"},
  {es:"viento", en:"wind", cat:"Sustantivos", ex:"hace mucho __viento__ — it's very windy"},
  {es:"lluvia", en:"rain", cat:"Sustantivos", ex:"no me gusta la __lluvia__ — I don't like rain"},
  {es:"nieve", en:"snow", cat:"Sustantivos", ex:"jugar en la __nieve__ — to play in the snow"},
  {es:"fuego", en:"fire", cat:"Sustantivos", ex:"cuidado con el __fuego__ — careful with the fire"},
  {es:"árbol", en:"tree", cat:"Sustantivos", ex:"un __árbol__ alto — a tall tree"},
  {es:"flor", en:"flower", cat:"Sustantivos", ex:"una __flor__ roja — a red flower"},
  {es:"bosque", en:"forest", cat:"Sustantivos", ex:"perderse en el __bosque__ — to get lost in the forest"},
  {es:"papel", en:"paper / role", cat:"Sustantivos", ex:"un trozo de __papel__ — a piece of paper"},
  {es:"bolígrafo", en:"pen", cat:"Sustantivos", ex:"préstame un __bolígrafo__ — lend me a pen"},
  {es:"carta", en:"letter / menu", cat:"Sustantivos", ex:"escribir una __carta__ — to write a letter"},
  {es:"foto", en:"photo", cat:"Sustantivos", ex:"hacer una __foto__ — to take a photo"},
  {es:"canción", en:"song", cat:"Sustantivos", ex:"cantar una __canción__ — to sing a song"},
  {es:"música", en:"music", cat:"Sustantivos", ex:"escuchar __música__ — to listen to music"},
  {es:"película", en:"movie", cat:"Sustantivos", ex:"ver una __película__ — to watch a movie"},
  {es:"juego", en:"game", cat:"Sustantivos", ex:"un __juego__ divertido — a fun game"},
  {es:"arte", en:"art", cat:"Sustantivos", ex:"el museo de __arte__ — the art museum"},
  {es:"historia", en:"history / story", cat:"Sustantivos", ex:"una __historia__ real — a true story"},
  {es:"verdad", en:"truth", cat:"Sustantivos", ex:"dime la __verdad__ — tell me the truth"},
  {es:"mentira", en:"lie", cat:"Sustantivos", ex:"eso es __mentira__ — that is a lie"},
  {es:"problema", en:"problem", cat:"Sustantivos", ex:"no hay __problema__ — there's no problem"},
  {es:"idea", en:"idea", cat:"Sustantivos", ex:"tengo una __idea__ — I have an idea"},
  {es:"pregunta", en:"question", cat:"Sustantivos", ex:"tengo una __pregunta__ — I have a question"},
  {es:"respuesta", en:"answer", cat:"Sustantivos", ex:"una buena __respuesta__ — a good answer"},
  {es:"razón", en:"reason / right", cat:"Sustantivos", ex:"tienes __razón__ — you are right"},
  {es:"cambio", en:"change", cat:"Sustantivos", ex:"un __cambio__ de planes — a change of plans"},
  {es:"ayuda", en:"help", cat:"Sustantivos", ex:"necesito __ayuda__ — I need help"},
  {es:"forma", en:"form / way / shape", cat:"Sustantivos", ex:"de ninguna __forma__ — no way"},
  {es:"manera", en:"way / manner", cat:"Sustantivos", ex:"de esta __manera__ — in this way"},
  {es:"cosa", en:"thing", cat:"Sustantivos", ex:"¿qué es esa __cosa__? — what is that thing?"},
  
  // --- BATCH 3 (200 New words, Spain Spanish focused) ---
  {es:"llevar", en:"to carry / take / wear", cat:"Verbos", ex:"tengo que __llevar__ esto — I have to carry this"},
  {es:"dejar", en:"to leave / let", cat:"Verbos", ex:"voy a __dejar__ el libro aquí — I will leave the book here"},
  {es:"llamar", en:"to call", cat:"Verbos", ex:"te voy a __llamar__ luego — I will call you later"},
  {es:"tomar", en:"to take / drink", cat:"Verbos", ex:"vamos a __tomar__ algo — let's have a drink"},
  {es:"creer", en:"to believe", cat:"Verbos", ex:"no me lo puedo __creer__ — I can't believe it"},
  {es:"deber", en:"must / should / to owe", cat:"Verbos", ex:"__debes__ estudiar más — you should study more"},
  {es:"quedar", en:"to stay / remain / meet", cat:"Verbos", ex:"¿a qué hora __quedamos__? — what time are we meeting?"},
  {es:"venir", en:"to come", cat:"Verbos", ex:"¿puedes __venir__ a mi casa? — can you come to my house?"},
  {es:"salir", en:"to go out / leave", cat:"Verbos", ex:"voy a __salir__ de fiesta — I'm going out to party"},
  {es:"volver", en:"to return / go back", cat:"Verbos", ex:"tengo que __volver__ al trabajo — I have to go back to work"},
  {es:"conocer", en:"to know (people/places)", cat:"Verbos", ex:"encantado de __conocerte__ — nice to meet you"},
  {es:"tratar", en:"to treat / try", cat:"Verbos", ex:"voy a __tratar__ de hacerlo — I will try to do it"},
  {es:"mirar", en:"to look at", cat:"Verbos", ex:"__mira__ esa foto — look at that photo"},
  {es:"contar", en:"to count / tell", cat:"Verbos", ex:"me tienes que __contar__ todo — you have to tell me everything"},
  {es:"esperar", en:"to wait / hope", cat:"Verbos", ex:"tengo que __esperar__ el tren — I have to wait for the train"},
  {es:"existir", en:"to exist", cat:"Verbos", ex:"eso no __existe__ — that doesn't exist"},
  {es:"entrar", en:"to enter", cat:"Verbos", ex:"puedes __entrar__ ahora — you can enter now"},
  {es:"escribir", en:"to write", cat:"Verbos", ex:"tengo que __escribir__ un email — I have to write an email"},
  {es:"perder", en:"to lose", cat:"Verbos", ex:"no quiero __perder__ — I don't want to lose"},
  {es:"producir", en:"to produce", cat:"Verbos", ex:"esta fábrica __produce__ coches — this factory produces cars"},
  {es:"ocurrir", en:"to happen / occur", cat:"Verbos", ex:"¿qué ha __ocurrido__? — what happened?"},
  {es:"pedir", en:"to ask for / order", cat:"Verbos", ex:"voy a __pedir__ una pizza — I'm going to order a pizza"},
  {es:"recibir", en:"to receive", cat:"Verbos", ex:"acabo de __recibir__ tu mensaje — I just received your message"},
  {es:"recordar", en:"to remember", cat:"Verbos", ex:"no puedo __recordar__ su nombre — I can't remember his name"},
  {es:"permitir", en:"to allow", cat:"Verbos", ex:"no se __permite__ fumar — smoking is not allowed"},
  {es:"aparecer", en:"to appear", cat:"Verbos", ex:"él __apareció__ de repente — he appeared suddenly"},
  {es:"conseguir", en:"to get / achieve", cat:"Verbos", ex:"tengo que __conseguir__ trabajo — I have to get a job"},
  {es:"comenzar", en:"to begin", cat:"Verbos", ex:"la clase va a __comenzar__ — the class is going to begin"},
  {es:"servir", en:"to serve / be useful", cat:"Verbos", ex:"¿para qué __sirve__ esto? — what is this used for?"},
  {es:"sacar", en:"to take out", cat:"Verbos", ex:"tengo que __sacar__ la basura — I have to take out the trash"},
  {es:"necesitar", en:"to need", cat:"Verbos", ex:"__necesito__ ayuda — I need help"},
  {es:"mantener", en:"to maintain / keep", cat:"Verbos", ex:"hay que __mantener__ la calma — you have to keep calm"},
  {es:"resultar", en:"to turn out / result", cat:"Verbos", ex:"__resultó__ ser verdad — it turned out to be true"},
  {es:"leer", en:"to read", cat:"Verbos", ex:"me gusta __leer__ libros — I like reading books"},
  {es:"caer", en:"to fall", cat:"Verbos", ex:"cuidado de no __caer__ — careful not to fall"},
  {es:"presentar", en:"to present", cat:"Verbos", ex:"te voy a __presentar__ a mi amigo — I'll introduce you to my friend"},
  {es:"crear", en:"to create", cat:"Verbos", ex:"vamos a __crear__ algo nuevo — we will create something new"},
  {es:"abrir", en:"to open", cat:"Verbos", ex:"voy a __abrir__ la ventana — I will open the window"},
  {es:"considerar", en:"to consider", cat:"Verbos", ex:"lo voy a __considerar__ — I will consider it"},
  {es:"oír", en:"to hear", cat:"Verbos", ex:"¿me puedes __oír__? — can you hear me?"},
  {es:"acabar", en:"to finish / end", cat:"Verbos", ex:"acabo de __acabar__ de comer — I just finished eating"},
  {es:"convertir", en:"to convert / change", cat:"Verbos", ex:"el agua se __convierte__ en hielo — water turns into ice"},
  {es:"ganar", en:"to win / earn", cat:"Verbos", ex:"quiero __ganar__ dinero — I want to earn money"},
  {es:"formar", en:"to form", cat:"Verbos", ex:"vamos a __formar__ un equipo — we'll form a team"},
  {es:"traer", en:"to bring", cat:"Verbos", ex:"¿puedes __traer__ el postre? — can you bring dessert?"},
  {es:"partir", en:"to divide / leave", cat:"Verbos", ex:"el tren está a punto de __partir__ — the train is about to leave"},
  {es:"morir", en:"to die", cat:"Verbos", ex:"me voy a __morir__ de risa — I'm going to die laughing"},
  {es:"aceptar", en:"to accept", cat:"Verbos", ex:"tienes que __aceptar__ la verdad — you have to accept the truth"},
  {es:"realizar", en:"to achieve / carry out", cat:"Verbos", ex:"vamos a __realizar__ un proyecto — we will carry out a project"},
  {es:"suponer", en:"to suppose", cat:"Verbos", ex:"__supongo__ que sí — I suppose so"},
  {es:"comprender", en:"to understand", cat:"Verbos", ex:"ahora lo __comprendo__ todo — now I understand everything"},
  {es:"lograr", en:"to achieve", cat:"Verbos", ex:"puedes __lograr__ tus metas — you can achieve your goals"},
  {es:"explicar", en:"to explain", cat:"Verbos", ex:"¿puedes __explicar__ eso? — can you explain that?"},
  {es:"preguntar", en:"to ask", cat:"Verbos", ex:"le voy a __preguntar__ — I'm going to ask him"},
  {es:"tocar", en:"to touch / play (instrument)", cat:"Verbos", ex:"no se puede __tocar__ — you can't touch it"},
  {es:"reconocer", en:"to recognize", cat:"Verbos", ex:"no te pude __reconocer__ — I couldn't recognize you"},
  {es:"estudiar", en:"to study", cat:"Verbos", ex:"tengo que __estudiar__ español — I have to study Spanish"},
  {es:"alcanzar", en:"to reach", cat:"Verbos", ex:"no puedo __alcanzar__ el libro — I can't reach the book"},
  {es:"nacer", en:"to be born", cat:"Verbos", ex:"yo __nací__ en España — I was born in Spain"},
  {es:"dirigir", en:"to direct / manage", cat:"Verbos", ex:"él __dirige__ la empresa — he manages the company"},
  {es:"correr", en:"to run", cat:"Verbos", ex:"voy a __correr__ al parque — I'm going to run in the park"},
  {es:"utilizar", en:"to use", cat:"Verbos", ex:"tienes que __utilizar__ esto — you have to use this"},
  {es:"pagar", en:"to pay", cat:"Verbos", ex:"¿puedo __pagar__ con tarjeta? — can I pay with a card?"},
  {es:"gustar", en:"to like", cat:"Verbos", ex:"me __gusta__ mucho — I like it a lot"},
  {es:"jugar", en:"to play", cat:"Verbos", ex:"vamos a __jugar__ al fútbol — let's play football"},
  {es:"cumplir", en:"to fulfill / carry out", cat:"Verbos", ex:"hay que __cumplir__ las reglas — one must follow the rules"},
  {es:"ofrecer", en:"to offer", cat:"Verbos", ex:"te voy a __ofrecer__ algo — I'm going to offer you something"},
  {es:"descubrir", en:"to discover", cat:"Verbos", ex:"quiero __descubrir__ cosas nuevas — I want to discover new things"},
  {es:"levantar", en:"to raise / lift", cat:"Verbos", ex:"__levanta__ la mano — raise your hand"},
  {es:"intentar", en:"to try", cat:"Verbos", ex:"voy a __intentar__ de nuevo — I will try again"},
  {es:"usar", en:"to use", cat:"Verbos", ex:"puedes __usar__ mi ordenador — you can use my computer"},
  {es:"tú", en:"you (informal singular)", cat:"Pronombres", ex:"__tú__ eres mi amigo — you are my friend"},
  {es:"usted", en:"you (formal singular)", cat:"Pronombres", ex:"¿__usted__ habla inglés? — do you speak English?"},
  {es:"ellos/ellas", en:"they", cat:"Pronombres", ex:"__ellos__ son de aquí — they are from here"},
  {es:"ustedes", en:"you (plural formal)", cat:"Pronombres", ex:"¿__ustedes__ qué piensan? — what do you all think?"},
  {es:"mí", en:"me (after prep)", cat:"Pronombres", ex:"esto es para __mí__ — this is for me"},
  {es:"ti", en:"you (after prep)", cat:"Pronombres", ex:"esto es para __ti__ — this is for you"},
  {es:"conmigo", en:"with me", cat:"Pronombres", ex:"ven __conmigo__ — come with me"},
  {es:"contigo", en:"with you", cat:"Pronombres", ex:"voy __contigo__ — I'm going with you"},
  {es:"sí (yes)", en:"yes", cat:"Afirmaciones", ex:"__sí__, claro — yes, of course"},
  {es:"sí (himself)", en:"himself / herself", cat:"Pronombres", ex:"habla consigo __mismo__ — he talks to himself"},
  {es:"qué", en:"what", cat:"Preguntas", ex:"¿__qué__ es esto? — what is this?"},
  {es:"cómo", en:"how", cat:"Preguntas", ex:"¿__cómo__ se hace? — how is it done?"},
  {es:"cuándo", en:"when", cat:"Preguntas", ex:"¿__cuándo__ vienes? — when are you coming?"},
  {es:"dónde", en:"where", cat:"Preguntas", ex:"¿__dónde__ vives? — where do you live?"},
  {es:"por qué", en:"why", cat:"Preguntas", ex:"¿__por qué__ no? — why not?"},
  {es:"quién", en:"who", cat:"Preguntas", ex:"¿__quién__ te lo dijo? — who told you?"},
  {es:"cuánto", en:"how much", cat:"Preguntas", ex:"¿__cuánto__ vale? — how much is it?"},
  {es:"cuál", en:"which", cat:"Preguntas", ex:"¿__cuál__ prefieres? — which one do you prefer?"},
  {es:"mío/mía", en:"mine", cat:"Pronombres", ex:"el coche es __mío__ — the car is mine"},
  {es:"tuyo/tuya", en:"yours", cat:"Pronombres", ex:"el libro es __tuyo__ — the book is yours"},
  {es:"suyo/suya", en:"his / hers / theirs", cat:"Pronombres", ex:"es el problema __suyo__ — it's his problem"},
  {es:"esto", en:"this (neutral)", cat:"Pronombres", ex:"__esto__ es muy raro — this is very weird"},
  {es:"eso", en:"that (neutral)", cat:"Pronombres", ex:"__eso__ no me gusta — I don't like that"},
  {es:"aquello", en:"that over there", cat:"Pronombres", ex:"__aquello__ fue genial — that was great"},
  {es:"sobre", en:"on / about / over", cat:"Preposiciones", ex:"el libro está __sobre__ la mesa — the book is on the table"},
  {es:"entre", en:"between / among", cat:"Preposiciones", ex:"está __entre__ los dos — it is between the two"},
  {es:"hacia", en:"towards", cat:"Preposiciones", ex:"vamos __hacia__ el sur — we are going towards the south"},
  {es:"desde", en:"from / since", cat:"Preposiciones", ex:"vivo aquí __desde__ enero — I live here since January"},
  {es:"sin", en:"without", cat:"Preposiciones", ex:"café __sin__ azúcar — coffee without sugar"},
  {es:"según", en:"according to", cat:"Preposiciones", ex:"__según__ las noticias — according to the news"},
  {es:"contra", en:"against", cat:"Preposiciones", ex:"está apoyado __contra__ la pared — it's leaning against the wall"},
  {es:"bajo", en:"under", cat:"Preposiciones", ex:"está __bajo__ control — it's under control"},
  {es:"hasta", en:"until / even", cat:"Preposiciones", ex:"__hasta__ luego — see you later"},
  {es:"alto", en:"tall / high", cat:"Adjetivos", ex:"es un edificio muy __alto__ — it's a very tall building"},
  {es:"bajo/baja", en:"short / low", cat:"Adjetivos", ex:"el techo es muy __bajo__ — the ceiling is very low"},
  {es:"largo", en:"long", cat:"Adjetivos", ex:"un viaje muy __largo__ — a very long trip"},
  {es:"corto", en:"short (length)", cat:"Adjetivos", ex:"tengo el pelo __corto__ — I have short hair"},
  {es:"ancho", en:"wide", cat:"Adjetivos", ex:"una calle muy __ancha__ — a very wide street"},
  {es:"estrecho", en:"narrow", cat:"Adjetivos", ex:"el pasillo es __estrecho__ — the hallway is narrow"},
  {es:"fuerte", en:"strong", cat:"Adjetivos", ex:"él es muy __fuerte__ — he is very strong"},
  {es:"débil", en:"weak", cat:"Adjetivos", ex:"me siento un poco __débil__ — I feel a bit weak"},
  {es:"claro", en:"clear / light", cat:"Adjetivos", ex:"está muy __claro__ — it's very clear"},
  {es:"oscuro", en:"dark", cat:"Adjetivos", ex:"esta habitación es __oscura__ — this room is dark"},
  {es:"lleno", en:"full", cat:"Adjetivos", ex:"el vaso está __lleno__ — the glass is full"},
  {es:"vacío", en:"empty", cat:"Adjetivos", ex:"la caja está __vacía__ — the box is empty"},
  {es:"rápido", en:"fast / quick", cat:"Adjetivos", ex:"el tren es muy __rápido__ — the train is very fast"},
  {es:"lento", en:"slow", cat:"Adjetivos", ex:"habla más __lento__, por favor — speak slower, please"},
  {es:"joven", en:"young", cat:"Adjetivos", ex:"es un chico muy __joven__ — he is a very young boy"},
  {es:"viejo", en:"old", cat:"Adjetivos", ex:"mi coche es muy __viejo__ — my car is very old"},
  {es:"blanco", en:"white", cat:"Adjetivos", ex:"una camiseta __blanca__ — a white t-shirt"},
  {es:"negro", en:"black", cat:"Adjetivos", ex:"tengo un gato __negro__ — I have a black cat"},
  {es:"rojo", en:"red", cat:"Adjetivos", ex:"me gusta el color __rojo__ — I like the color red"},
  {es:"azul", en:"blue", cat:"Adjetivos", ex:"el cielo es __azul__ — the sky is blue"},
  {es:"verde", en:"green", cat:"Adjetivos", ex:"una manzana __verde__ — a green apple"},
  {es:"amarillo", en:"yellow", cat:"Adjetivos", ex:"el sol es __amarillo__ — the sun is yellow"},
  {es:"rico", en:"rich / tasty", cat:"Adjetivos", ex:"esta comida está muy __rica__ — this food is very tasty"},
  {es:"pobre", en:"poor", cat:"Adjetivos", ex:"un país __pobre__ — a poor country"},
  {es:"igual", en:"equal / same", cat:"Adjetivos", ex:"son exactamente __iguales__ — they are exactly the same"},
  {es:"distinto", en:"different", cat:"Adjetivos", ex:"es una situación __distinta__ — it's a different situation"},
  {es:"solo", en:"alone / only", cat:"Adjetivos", ex:"estoy __solo__ en casa — I'm alone at home"},
  {es:"único", en:"unique / only", cat:"Adjetivos", ex:"es mi __único__ hermano — he is my only brother"},
  {es:"peor", en:"worse", cat:"Adjetivos", ex:"es el __peor__ día de mi vida — it's the worst day of my life"},
  {es:"mejor", en:"better / best", cat:"Adjetivos", ex:"es la __mejor__ película — it's the best movie"},
  {es:"mayor", en:"older / larger", cat:"Adjetivos", ex:"mi hermano __mayor__ — my older brother"},
  {es:"menor", en:"younger / smaller", cat:"Adjetivos", ex:"mi hermana __menor__ — my younger sister"},
  {es:"posible", en:"possible", cat:"Adjetivos", ex:"es __posible__ que llueva — it's possible that it will rain"},
  {es:"imposible", en:"impossible", cat:"Adjetivos", ex:"eso es __imposible__ — that is impossible"},
  {es:"verdadero", en:"true / real", cat:"Adjetivos", ex:"es un amigo __verdadero__ — he is a true friend"},
  {es:"falso", en:"false / fake", cat:"Adjetivos", ex:"eso es totalmente __falso__ — that is totally false"},
  {es:"abierto", en:"open", cat:"Adjetivos", ex:"la puerta está __abierta__ — the door is open"},
  {es:"cerrado", en:"closed", cat:"Adjetivos", ex:"el bar está __cerrado__ — the bar is closed"},
  {es:"frío", en:"cold", cat:"Adjetivos", ex:"el agua está __fría__ — the water is cold"},
  {es:"caliente", en:"hot", cat:"Adjetivos", ex:"un café __caliente__ — a hot coffee"},
  {es:"limpio", en:"clean", cat:"Adjetivos", ex:"mi cuarto está __limpio__ — my room is clean"},
  {es:"sucio", en:"dirty", cat:"Adjetivos", ex:"el suelo está __sucio__ — the floor is dirty"},
  {es:"bonito", en:"pretty", cat:"Adjetivos", ex:"es un vestido muy __bonito__ — it's a very pretty dress"},
  {es:"feo", en:"ugly", cat:"Adjetivos", ex:"ese edificio es muy __feo__ — that building is very ugly"},
  {es:"barato", en:"cheap", cat:"Adjetivos", ex:"es muy __barato__ comprar aquí — it's very cheap to buy here"},
  {es:"caro", en:"expensive", cat:"Adjetivos", ex:"ese coche es demasiado __caro__ — that car is too expensive"},
  {es:"cero", en:"zero", cat:"Números", ex:"empezamos de __cero__ — we start from zero"},
  {es:"cuatro", en:"four", cat:"Números", ex:"tengo __cuatro__ hermanos — I have four siblings"},
  {es:"seis", en:"six", cat:"Números", ex:"son las __seis__ de la tarde — it's six in the afternoon"},
  {es:"siete", en:"seven", cat:"Números", ex:"__siete__ días de la semana — seven days of the week"},
  {es:"ocho", en:"eight", cat:"Números", ex:"trabajo __ocho__ horas — I work eight hours"},
  {es:"nueve", en:"nine", cat:"Números", ex:"a las __nueve__ en punto — at nine o'clock"},
  {es:"once", en:"eleven", cat:"Números", ex:"tiene __once__ años — he is eleven years old"},
  {es:"doce", en:"twelve", cat:"Números", ex:"doce meses — __twelve__ months"},
  {es:"veinte", en:"twenty", cat:"Números", ex:"cuesta __veinte__ euros — it costs twenty euros"},
  {es:"treinta", en:"thirty", cat:"Números", ex:"__treinta__ días tiene noviembre — November has thirty days"},
  {es:"cuarenta", en:"forty", cat:"Números", ex:"él tiene __cuarenta__ años — he is forty years old"},
  {es:"cincuenta", en:"fifty", cat:"Números", ex:"pagamos __cincuenta__ euros — we paid fifty euros"},
  {es:"cien", en:"one hundred", cat:"Números", ex:"cuesta casi __cien__ euros — it costs almost one hundred euros"},
  {es:"mil", en:"one thousand", cat:"Números", ex:"__mil__ gracias — a thousand thanks"},
  {es:"primero", en:"first", cat:"Números", ex:"es mi __primer__ coche — it's my first car"},
  {es:"segundo (adj)", en:"second", cat:"Números", ex:"vivo en el __segundo__ piso — I live on the second floor"},
  {es:"tercero", en:"third", cat:"Números", ex:"es la __tercera__ vez que te llamo — it's the third time I call you"},
  {es:"último", en:"last", cat:"Números", ex:"el __último__ tren — the last train"},
  {es:"próximo", en:"next", cat:"Adjetivos", ex:"el __próximo__ año — next year"},
  {es:"siguiente", en:"following / next", cat:"Adjetivos", ex:"el día __siguiente__ — the following day"},
  {es:"pasado", en:"past / last", cat:"Adjetivos", ex:"el año __pasado__ — last year"},
  {es:"futuro", en:"future", cat:"Sustantivos", ex:"pensar en el __futuro__ — to think about the future"},
  {es:"mitad", en:"half", cat:"Números", ex:"quiero la __mitad__ — I want half"},
  {es:"poco", en:"little / few", cat:"Adjetivos", ex:"tengo __poco__ tiempo — I have little time"},
  {es:"mucho", en:"a lot / much", cat:"Adjetivos", ex:"hace __mucho__ calor — it's very hot"},
  {es:"demasiado", en:"too much", cat:"Adjetivos", ex:"es __demasiado__ caro — it's too expensive"},
  {es:"bastante", en:"enough / quite a lot", cat:"Adjetivos", ex:"es __bastante__ grande — it's quite big"},
  {es:"suficiente", en:"sufficient / enough", cat:"Adjetivos", ex:"ya es __suficiente__ — that's enough"},
  {es:"casi", en:"almost", cat:"Gramática", ex:"ya __casi__ terminamos — we are almost done"},
  {es:"solo (adv)", en:"only / just", cat:"Gramática", ex:"__solo__ quiero agua — I only want water"},
  {es:"además", en:"besides / furthermore", cat:"Gramática", ex:"__además__, no tengo dinero — besides, I have no money"},
  {es:"también", en:"also / too", cat:"Gramática", ex:"yo __también__ voy — I am also going"},
  {es:"tampoco", en:"neither / not either", cat:"Gramática", ex:"yo __tampoco__ lo sé — I don't know either"},
  {es:"entonces", en:"then", cat:"Gramática", ex:"__entonces__, ¿qué hacemos? — then, what do we do?"},
  {es:"luego (adv)", en:"then / later", cat:"Gramática", ex:"vamos a cenar y __luego__ al cine — let's have dinner and then the movies"},
  {es:"así que", en:"so", cat:"Gramática", ex:"estaba lloviendo, __así que__ me quedé — it was raining, so I stayed"},
  {es:"por eso", en:"that's why", cat:"Gramática", ex:"estaba enfermo, __por eso__ no fui — I was sick, that's why I didn't go"},
  {es:"aunque", en:"although / even though", cat:"Gramática", ex:"iré __aunque__ llueva — I will go even though it rains"},
  {es:"mientras que", en:"while (contrast)", cat:"Gramática", ex:"yo trabajo, __mientras que__ tú duermes — I work, while you sleep"},
  {es:"sin embargo", en:"however", cat:"Gramática", ex:"es caro, __sin embargo__ lo compraré — it's expensive, however I will buy it"},
  
  // --- BATCH 4 (200 New words, Spain Spanish focused) ---
  {es:"olvidar", en:"to forget", cat:"Verbos", ex:"no te vayas a __olvidar__ — don't forget"},
  {es:"volar", en:"to fly", cat:"Verbos", ex:"el pájaro puede __volar__ — the bird can fly"},
  {es:"andar", en:"to walk", cat:"Verbos", ex:"vamos a __andar__ un poco — let's walk a bit"},
  {es:"elegir", en:"to choose", cat:"Verbos", ex:"tienes que __elegir__ uno — you have to choose one"},
  {es:"mostrar", en:"to show", cat:"Verbos", ex:"¿me puedes __mostrar__ eso? — can you show me that?"},
  {es:"sufrir", en:"to suffer", cat:"Verbos", ex:"no quiero __sufrir__ más — I don't want to suffer anymore"},
  {es:"valer", en:"to be worth / cost", cat:"Verbos", ex:"¿cuánto __vale__ esto? — how much is this worth?"},
  {es:"preferir", en:"to prefer", cat:"Verbos", ex:"yo __prefiero__ el té — I prefer tea"},
  {es:"subir", en:"to go up / climb", cat:"Verbos", ex:"vamos a __subir__ las escaleras — let's go up the stairs"},
  {es:"bajar", en:"to go down / lower", cat:"Verbos", ex:"voy a __bajar__ a la calle — I'm going down to the street"},
  {es:"enviar", en:"to send", cat:"Verbos", ex:"tengo que __enviar__ un paquete — I have to send a package"},
  {es:"mandar", en:"to send / order", cat:"Verbos", ex:"te voy a __mandar__ un mensaje — I will send you a message"},
  {es:"cruzar", en:"to cross", cat:"Verbos", ex:"ten cuidado al __cruzar__ — be careful when crossing"},
  {es:"enseñar", en:"to teach / show", cat:"Verbos", ex:"me gusta __enseñar__ español — I like teaching Spanish"},
  {es:"saltar", en:"to jump", cat:"Verbos", ex:"el perro empezó a __saltar__ — the dog started jumping"},
  {es:"gastar", en:"to spend (money)", cat:"Verbos", ex:"no quiero __gastar__ mucho — I don't want to spend a lot"},
  {es:"vender", en:"to sell", cat:"Verbos", ex:"vamos a __vender__ el coche — we're going to sell the car"},
  {es:"comprar", en:"to buy", cat:"Verbos", ex:"necesito __comprar__ leche — I need to buy milk"},
  {es:"reír", en:"to laugh", cat:"Verbos", ex:"me haces __reír__ — you make me laugh"},
  {es:"llorar", en:"to cry", cat:"Verbos", ex:"el bebé no para de __llorar__ — the baby won't stop crying"},
  {es:"firmar", en:"to sign", cat:"Verbos", ex:"tienes que __firmar__ aquí — you have to sign here"},
  {es:"cortar", en:"to cut", cat:"Verbos", ex:"cuidado al __cortar__ el pan — be careful cutting the bread"},
  {es:"cocinar", en:"to cook", cat:"Verbos", ex:"me encanta __cocinar__ — I love cooking"},
  {es:"probar", en:"to try / taste", cat:"Verbos", ex:"quieres __probar__ un poco? — do you want to taste a bit?"},
  {es:"pintar", en:"to paint", cat:"Verbos", ex:"vamos a __pintar__ la casa — we're going to paint the house"},
  {es:"cantar", en:"to sing", cat:"Verbos", ex:"canta una __canción__ — sing a song"},
  {es:"limpiar", en:"to clean", cat:"Verbos", ex:"hoy toca __limpiar__ — today it's time to clean"},
  {es:"arreglar", en:"to fix / arrange", cat:"Verbos", ex:"tengo que __arreglar__ esto — I have to fix this"},
  {es:"amar", en:"to love", cat:"Verbos", ex:"te voy a __amar__ siempre — I will love you always"},
  {es:"odiar", en:"to hate", cat:"Verbos", ex:"__odio__ levantarme temprano — I hate getting up early"},
  {es:"continuar", en:"to continue", cat:"Verbos", ex:"debemos __continuar__ — we must continue"},
  {es:"iniciar", en:"to initiate / start", cat:"Verbos", ex:"vamos a __iniciar__ la sesión — let's start the session"},
  {es:"romper", en:"to break", cat:"Verbos", ex:"se acaba de __romper__ el vaso — the glass just broke"},
  {es:"pegar", en:"to hit / paste", cat:"Verbos", ex:"no le puedes __pegar__ — you can't hit him"},
  {es:"dibujar", en:"to draw", cat:"Verbos", ex:"a la niña le gusta __dibujar__ — the girl likes to draw"},
  {es:"llenar", en:"to fill", cat:"Verbos", ex:"hay que __llenar__ el depósito — we have to fill the tank"},
  {es:"quemar", en:"to burn", cat:"Verbos", ex:"cuidado de no __quemar__ la comida — careful not to burn the food"},
  {es:"matar", en:"to kill", cat:"Verbos", ex:"eso te va a __matar__ — that's going to kill you"},
  {es:"salvar", en:"to save", cat:"Verbos", ex:"él logró __salvar__ al perro — he managed to save the dog"},
  {es:"descansar", en:"to rest", cat:"Verbos", ex:"necesitas __descansar__ un poco — you need to rest a bit"},
  {es:"respirar", en:"to breathe", cat:"Verbos", ex:"es difícil __respirar__ aquí — it's hard to breathe here"},
  {es:"soñar", en:"to dream", cat:"Verbos", ex:"me gusta __soñar__ contigo — I like dreaming of you"},
  {es:"despertar", en:"to wake up", cat:"Verbos", ex:"me cuesta __despertar__ — it's hard for me to wake up"},
  {es:"empujar", en:"to push", cat:"Verbos", ex:"no me vuelvas a __empujar__ — don't push me again"},
  {es:"tirar", en:"to throw / pull", cat:"Verbos", ex:"hay que __tirar__ de la puerta — you have to pull the door"},
  {es:"echar", en:"to throw / pour", cat:"Verbos", ex:"te voy a __echar__ de menos — I'm going to miss you"},
  {es:"agarrar", en:"to grab", cat:"Verbos", ex:"__agarra__ bien el volante — grab the steering wheel well"},
  {es:"compartir", en:"to share", cat:"Verbos", ex:"me gusta __compartir__ mis cosas — I like sharing my things"},
  {es:"evitar", en:"to avoid", cat:"Verbos", ex:"debemos __evitar__ los problemas — we must avoid problems"},
  {es:"conducir", en:"to drive", cat:"Verbos", ex:"no me gusta __conducir__ de noche — I don't like driving at night"},
  {es:"vaso", en:"glass (drinking)", cat:"Sustantivos", ex:"un __vaso__ de agua — a glass of water"},
  {es:"plato", en:"plate / dish", cat:"Sustantivos", ex:"mi __plato__ favorito — my favorite dish"},
  {es:"taza", en:"cup / mug", cat:"Sustantivos", ex:"una __taza__ de café — a cup of coffee"},
  {es:"tenedor", en:"fork", cat:"Sustantivos", ex:"necesito un __tenedor__ — I need a fork"},
  {es:"cuchillo", en:"knife", cat:"Sustantivos", ex:"corta con el __cuchillo__ — cut with the knife"},
  {es:"cuchara", en:"spoon", cat:"Sustantivos", ex:"toma la sopa con __cuchara__ — eat the soup with a spoon"},
  {es:"olla", en:"pot", cat:"Sustantivos", ex:"pon agua en la __olla__ — put water in the pot"},
  {es:"sartén", en:"frying pan", cat:"Sustantivos", ex:"fríe el huevo en la __sartén__ — fry the egg in the pan"},
  {es:"botella", en:"bottle", cat:"Sustantivos", ex:"una __botella__ de vino — a bottle of wine"},
  {es:"servilleta", en:"napkin", cat:"Sustantivos", ex:"¿me das una __servilleta__? — can you give me a napkin?"},
  {es:"toalla", en:"towel", cat:"Sustantivos", ex:"sécate con la __toalla__ — dry yourself with the towel"},
  {es:"jabón", en:"soap", cat:"Sustantivos", ex:"lávate con agua y __jabón__ — wash with water and soap"},
  {es:"champú", en:"shampoo", cat:"Sustantivos", ex:"no me queda __champú__ — I'm out of shampoo"},
  {es:"cepillo", en:"brush", cat:"Sustantivos", ex:"un __cepillo__ de dientes — a toothbrush"},
  {es:"espejo", en:"mirror", cat:"Sustantivos", ex:"mírate en el __espejo__ — look at yourself in the mirror"},
  {es:"lavabo", en:"sink", cat:"Sustantivos", ex:"lávate las manos en el __lavabo__ — wash your hands in the sink"},
  {es:"ducha", en:"shower", cat:"Sustantivos", ex:"me voy a dar una __ducha__ — I'm going to take a shower"},
  {es:"almohada", en:"pillow", cat:"Sustantivos", ex:"esta __almohada__ es muy suave — this pillow is very soft"},
  {es:"sábana", en:"sheet (bed)", cat:"Sustantivos", ex:"hay que cambiar las __sábanas__ — we have to change the sheets"},
  {es:"manta", en:"blanket", cat:"Sustantivos", ex:"tengo frío, dame una __manta__ — I'm cold, give me a blanket"},
  {es:"armario", en:"closet / wardrobe", cat:"Sustantivos", ex:"guarda la ropa en el __armario__ — keep the clothes in the closet"},
  {es:"sofá", en:"sofa", cat:"Sustantivos", ex:"siéntate en el __sofá__ — sit on the sofa"},
  {es:"sillón", en:"armchair", cat:"Sustantivos", ex:"el abuelo descansa en el __sillón__ — grandpa rests in the armchair"},
  {es:"lámpara", en:"lamp", cat:"Sustantivos", ex:"enciende la __lámpara__ — turn on the lamp"},
  {es:"alfombra", en:"rug", cat:"Sustantivos", ex:"limpia la __alfombra__ — clean the rug"},
  {es:"cuadro", en:"painting / picture", cat:"Sustantivos", ex:"ese __cuadro__ es muy antiguo — that painting is very old"},
  {es:"reloj", en:"clock / watch", cat:"Sustantivos", ex:"¿qué hora marca el __reloj__? — what time does the clock show?"},
  {es:"candado", en:"padlock", cat:"Sustantivos", ex:"ponle un __candado__ a la bici — put a padlock on the bike"},
  {es:"escalera", en:"stairs / ladder", cat:"Sustantivos", ex:"sube por la __escalera__ — go up the stairs"},
  {es:"ascensor", en:"elevator", cat:"Sustantivos", ex:"el __ascensor__ está roto — the elevator is broken"},
  {es:"balcón", en:"balcony", cat:"Sustantivos", ex:"sal al __balcón__ a mirar — go out to the balcony to look"},
  {es:"jardín", en:"garden", cat:"Sustantivos", ex:"las flores del __jardín__ — the garden flowers"},
  {es:"garaje", en:"garage", cat:"Sustantivos", ex:"aparca en el __garaje__ — park in the garage"},
  {es:"avenida", en:"avenue", cat:"Sustantivos", ex:"paseo por la gran __avenida__ — I stroll down the grand avenue"},
  {es:"puente", en:"bridge", cat:"Sustantivos", ex:"cruza el __puente__ — cross the bridge"},
  {es:"moto", en:"motorcycle", cat:"Sustantivos", ex:"viajar en __moto__ — to travel by motorcycle"},
  {es:"bicicleta", en:"bicycle / bike", cat:"Sustantivos", ex:"vamos en __bicicleta__ — let's go by bike"},
  {es:"camión", en:"truck", cat:"Sustantivos", ex:"un __camión__ de reparto — a delivery truck"},
  {es:"barco", en:"boat / ship", cat:"Sustantivos", ex:"un viaje en __barco__ — a boat trip"},
  {es:"avión", en:"airplane", cat:"Sustantivos", ex:"el __avión__ despega ahora — the plane takes off now"},
  {es:"tren", en:"train", cat:"Sustantivos", ex:"perdimos el __tren__ — we missed the train"},
  {es:"médico/médica", en:"doctor", cat:"Sustantivos", ex:"voy al __médico__ hoy — I'm going to the doctor today"},
  {es:"doctor/doctora", en:"doctor", cat:"Sustantivos", ex:"la __doctora__ te verá ahora — the doctor will see you now"},
  {es:"enfermero/enfermera", en:"nurse", cat:"Sustantivos", ex:"el __enfermero__ me sacó sangre — the nurse drew my blood"},
  {es:"profesor/profesora", en:"professor / teacher", cat:"Sustantivos", ex:"es mi __profesor__ de español — he is my Spanish teacher"},
  {es:"maestro/maestra", en:"teacher", cat:"Sustantivos", ex:"la __maestra__ de primaria — the elementary school teacher"},
  {es:"policía", en:"police / police officer", cat:"Sustantivos", ex:"llama a la __policía__ — call the police"},
  {es:"bombero", en:"firefighter", cat:"Sustantivos", ex:"los __bomberos__ apagaron el fuego — the firefighters put out the fire"},
  {es:"abogado/abogada", en:"lawyer", cat:"Sustantivos", ex:"mi __abogado__ me asesora — my lawyer advises me"},
  {es:"juez", en:"judge", cat:"Sustantivos", ex:"el __juez__ dictó sentencia — the judge passed sentence"},
  {es:"estudiante", en:"student", cat:"Sustantivos", ex:"soy un __estudiante__ universitario — I'm a university student"},
  {es:"alumno/alumna", en:"pupil / student", cat:"Sustantivos", ex:"es un __alumno__ brillante — he's a brilliant pupil"},
  {es:"escritor/escritora", en:"writer", cat:"Sustantivos", ex:"un famoso __escritor__ español — a famous Spanish writer"},
  {es:"actor", en:"actor", cat:"Sustantivos", ex:"el __actor__ principal — the lead actor"},
  {es:"actriz", en:"actress", cat:"Sustantivos", ex:"ganó el premio a mejor __actriz__ — she won best actress"},
  {es:"cantante", en:"singer", cat:"Sustantivos", ex:"es mi __cantante__ favorito — he is my favorite singer"},
  {es:"camarero/camarera", en:"waiter", cat:"Sustantivos", ex:"perdona, __camarero__ — excuse me, waiter"},
  {es:"cocinero/cocinera", en:"cook / chef", cat:"Sustantivos", ex:"el __cocinero__ prepara la cena — the chef prepares dinner"},
  {es:"panadero", en:"baker", cat:"Sustantivos", ex:"el __panadero__ hace el pan — the baker makes the bread"},
  {es:"carpintero", en:"carpenter", cat:"Sustantivos", ex:"el __carpintero__ hizo la mesa — the carpenter made the table"},
  {es:"pintor", en:"painter", cat:"Sustantivos", ex:"es un __pintor__ muy talentoso — he is a very talented painter"},
  {es:"conductor", en:"driver", cat:"Sustantivos", ex:"el __conductor__ del autobús — the bus driver"},
  {es:"dependiente/dependienta", en:"clerk / shop assistant", cat:"Sustantivos", ex:"pregunta a la __dependienta__ — ask the shop assistant"},
  {es:"cliente", en:"client / customer", cat:"Sustantivos", ex:"el __cliente__ siempre tiene la razón — the customer is always right"},
  {es:"secretario/secretaria", en:"secretary", cat:"Sustantivos", ex:"habla con mi __secretaria__ — talk to my secretary"},
  {es:"director/directora", en:"director / manager", cat:"Sustantivos", ex:"el __director__ de la película — the movie's director"},
  {es:"presidente/presidenta", en:"president", cat:"Sustantivos", ex:"el __presidente__ del gobierno — the prime minister (president)"},
  {es:"rey", en:"king", cat:"Sustantivos", ex:"el __rey__ de España — the king of Spain"},
  {es:"reina", en:"queen", cat:"Sustantivos", ex:"la __reina__ saluda — the queen waves"},
  {es:"banco", en:"bank / bench", cat:"Sustantivos", ex:"voy al __banco__ a sacar dinero — I'm going to the bank to get money"},
  {es:"hospital", en:"hospital", cat:"Sustantivos", ex:"está ingresado en el __hospital__ — he is admitted to the hospital"},
  {es:"farmacia", en:"pharmacy", cat:"Sustantivos", ex:"compra las pastillas en la __farmacia__ — buy the pills at the pharmacy"},
  {es:"supermercado", en:"supermarket", cat:"Sustantivos", ex:"hacer la compra en el __supermercado__ — to shop at the supermarket"},
  {es:"mercado", en:"market", cat:"Sustantivos", ex:"fruta fresca del __mercado__ — fresh fruit from the market"},
  {es:"tienda", en:"shop / store", cat:"Sustantivos", ex:"una __tienda__ de ropa — a clothing store"},
  {es:"restaurante", en:"restaurant", cat:"Sustantivos", ex:"vamos a cenar a un __restaurante__ — let's have dinner at a restaurant"},
  {es:"hotel", en:"hotel", cat:"Sustantivos", ex:"dormir en un buen __hotel__ — to sleep in a good hotel"},
  {es:"museo", en:"museum", cat:"Sustantivos", ex:"visitar el __museo__ de arte — to visit the art museum"},
  {es:"teatro", en:"theater", cat:"Sustantivos", ex:"ver una obra de __teatro__ — to see a play"},
  {es:"cine", en:"cinema / movies", cat:"Sustantivos", ex:"esta tarde vamos al __cine__ — this afternoon we go to the movies"},
  {es:"biblioteca", en:"library", cat:"Sustantivos", ex:"estudiar en la __biblioteca__ — to study in the library"},
  {es:"iglesia", en:"church", cat:"Sustantivos", ex:"la campana de la __iglesia__ — the church bell"},
  {es:"parque", en:"park", cat:"Sustantivos", ex:"pasear por el __parque__ — to walk through the park"},
  {es:"piscina", en:"swimming pool", cat:"Sustantivos", ex:"nadar en la __piscina__ — to swim in the pool"},
  {es:"gimnasio", en:"gym", cat:"Sustantivos", ex:"hacer ejercicio en el __gimnasio__ — to exercise in the gym"},
  {es:"campo", en:"countryside / field", cat:"Sustantivos", ex:"pasar el fin de semana en el __campo__ — to spend the weekend in the countryside"},
  {es:"cerdo", en:"pig / pork", cat:"Sustantivos", ex:"la carne de __cerdo__ — pork meat"},
  {es:"vaca", en:"cow", cat:"Sustantivos", ex:"la __vaca__ da leche — the cow gives milk"},
  {es:"oveja", en:"sheep", cat:"Sustantivos", ex:"el rebaño de __ovejas__ — the flock of sheep"},
  {es:"cabra", en:"goat", cat:"Sustantivos", ex:"queso de __cabra__ — goat cheese"},
  {es:"toro", en:"bull", cat:"Sustantivos", ex:"correr delante del __toro__ — to run in front of the bull"},
  {es:"gallina", en:"hen", cat:"Sustantivos", ex:"la __gallina__ pone huevos — the hen lays eggs"},
  {es:"pato", en:"duck", cat:"Sustantivos", ex:"el __pato__ nada en el lago — the duck swims in the lake"},
  {es:"conejo", en:"rabbit", cat:"Sustantivos", ex:"el __conejo__ come zanahorias — the rabbit eats carrots"},
  {es:"ratón", en:"mouse", cat:"Sustantivos", ex:"el __ratón__ huyó del gato — the mouse fled from the cat"},
  {es:"león", en:"lion", cat:"Sustantivos", ex:"el rugido del __león__ — the lion's roar"},
  {es:"tigre", en:"tiger", cat:"Sustantivos", ex:"un __tigre__ de bengala — a bengal tiger"},
  {es:"oso", en:"bear", cat:"Sustantivos", ex:"un __oso__ pardo — a brown bear"},
  {es:"mono", en:"monkey / cute", cat:"Sustantivos", ex:"¡qué niño más __mono__! — what a cute boy! (or: a monkey)"},
  {es:"elefante", en:"elephant", cat:"Sustantivos", ex:"el __elefante__ tiene trompa — the elephant has a trunk"},
  {es:"jirafa", en:"giraffe", cat:"Sustantivos", ex:"la __jirafa__ tiene el cuello largo — the giraffe has a long neck"},
  {es:"serpiente", en:"snake", cat:"Sustantivos", ex:"cuidado con la __serpiente__ — careful with the snake"},
  {es:"pez", en:"fish (alive)", cat:"Sustantivos", ex:"el __pez__ nada en la pecera — the fish swims in the fish tank"},
  {es:"tiburón", en:"shark", cat:"Sustantivos", ex:"un ataque de __tiburón__ — a shark attack"},
  {es:"ballena", en:"whale", cat:"Sustantivos", ex:"ver __ballenas__ en el mar — to see whales in the sea"},
  {es:"mosca", en:"fly", cat:"Sustantivos", ex:"hay una __mosca__ en mi sopa — there's a fly in my soup"},
  {es:"mosquito", en:"mosquito", cat:"Sustantivos", ex:"me ha picado un __mosquito__ — a mosquito bit me"},
  {es:"araña", en:"spider", cat:"Sustantivos", ex:"tengo miedo a las __arañas__ — I'm afraid of spiders"},
  {es:"gris", en:"gray", cat:"Adjetivos", ex:"un día nublado y __gris__ — a cloudy and gray day"},
  {es:"rosa", en:"pink", cat:"Adjetivos", ex:"un chicle de color __rosa__ — a pink gum"},
  {es:"marrón", en:"brown", cat:"Adjetivos", ex:"ojos color __marrón__ — brown eyes"},
  {es:"morado", en:"purple", cat:"Adjetivos", ex:"un vestido __morado__ — a purple dress"},
  {es:"violeta", en:"violet", cat:"Adjetivos", ex:"me gusta el color __violeta__ — I like the color violet"},
  {es:"adelante", en:"forward / go ahead", cat:"Gramática", ex:"sigue __adelante__ — keep going forward"},
  {es:"atrás", en:"back / backwards", cat:"Gramática", ex:"da un paso hacia __atrás__ — take a step back"},
  {es:"despacio", en:"slowly", cat:"Gramática", ex:"habla más __despacio__ — speak slower"},
  {es:"deprisa", en:"in a hurry / fast", cat:"Gramática", ex:"voy muy __deprisa__ — I'm in a big hurry"},
  {es:"seguro", en:"sure / safe", cat:"Adjetivos", ex:"¿estás __seguro__? — are you sure?"},
  {es:"peligro", en:"danger", cat:"Sustantivos", ex:"está fuera de __peligro__ — he is out of danger"},
  {es:"cuidado", en:"care / careful", cat:"Sustantivos", ex:"¡ten __cuidado__! — be careful!"},
  {es:"suerte", en:"luck", cat:"Sustantivos", ex:"¡buena __suerte__! — good luck!"},
  {es:"éxito", en:"success", cat:"Sustantivos", ex:"fue un gran __éxito__ — it was a huge success"},
  {es:"fracaso", en:"failure", cat:"Sustantivos", ex:"el proyecto fue un __fracaso__ — the project was a failure"},
  {es:"dedo", en:"finger / toe", cat:"Sustantivos", ex:"me corté el __dedo__ — I cut my finger"},
  {es:"uña", en:"nail", cat:"Sustantivos", ex:"píntate las __uñas__ — paint your nails"},
  {es:"pelo", en:"hair", cat:"Sustantivos", ex:"tiene el __pelo__ rubio — he has blonde hair"},
  {es:"oreja", en:"ear", cat:"Sustantivos", ex:"me duele la __oreja__ — my ear hurts"},
  {es:"nariz", en:"nose", cat:"Sustantivos", ex:"tengo la __nariz__ fría — my nose is cold"},
  {es:"labio", en:"lip", cat:"Sustantivos", ex:"se mordió el __labio__ — he bit his lip"},
  {es:"diente", en:"tooth", cat:"Sustantivos", ex:"lávate los __dientes__ — brush your teeth"},
  {es:"lengua", en:"tongue / language", cat:"Sustantivos", ex:"me quemé la __lengua__ — I burned my tongue"},
  {es:"cuello", en:"neck", cat:"Sustantivos", ex:"me duele el __cuello__ — my neck hurts"},
  {es:"hombro", en:"shoulder", cat:"Sustantivos", ex:"un golpe en el __hombro__ — a hit on the shoulder"},
  {es:"pecho", en:"chest", cat:"Sustantivos", ex:"siente un dolor en el __pecho__ — feels a pain in the chest"},
  {es:"barriga", en:"belly", cat:"Sustantivos", ex:"tengo dolor de __barriga__ — I have a bellyache"},
  {es:"estómago", en:"stomach", cat:"Sustantivos", ex:"un problema de __estómago__ — a stomach problem"},
  {es:"rodilla", en:"knee", cat:"Sustantivos", ex:"se cayó y se peló la __rodilla__ — he fell and scraped his knee"},
  {es:"tobillo", en:"ankle", cat:"Sustantivos", ex:"me torcí el __tobillo__ — I sprained my ankle"},
  {es:"sangre", en:"blood", cat:"Sustantivos", ex:"yo dono __sangre__ — I donate blood"},
  {es:"hueso", en:"bone", cat:"Sustantivos", ex:"se rompió un __hueso__ — he broke a bone"},
  {es:"piel", en:"skin", cat:"Sustantivos", ex:"tengo la __piel__ seca — I have dry skin"},
  
  // --- BATCH 5 (Final 270 words, Spain Spanish focused) ---
  {es:"uva", en:"grape", cat:"Sustantivos", ex:"un racimo de __uvas__ — a bunch of grapes"},
  {es:"plátano", en:"banana", cat:"Sustantivos", ex:"el __plátano__ es amarillo — the banana is yellow"},
  {es:"fresa", en:"strawberry", cat:"Sustantivos", ex:"me gusta el helado de __fresa__ — I like strawberry ice cream"},
  {es:"pera", en:"pear", cat:"Sustantivos", ex:"una __pera__ madura — a ripe pear"},
  {es:"limón", en:"lemon", cat:"Sustantivos", ex:"un té con __limón__ — a tea with lemon"},
  {es:"tomate", en:"tomato", cat:"Sustantivos", ex:"ensalada de __tomate__ — tomato salad"},
  {es:"cebolla", en:"onion", cat:"Sustantivos", ex:"lloro al cortar la __cebolla__ — I cry when cutting the onion"},
  {es:"ajo", en:"garlic", cat:"Sustantivos", ex:"huele mucho a __ajo__ — it smells a lot like garlic"},
  {es:"pimiento", en:"pepper", cat:"Sustantivos", ex:"__pimiento__ rojo asado — roasted red pepper"},
  {es:"zanahoria", en:"carrot", cat:"Sustantivos", ex:"el conejo come __zanahorias__ — the rabbit eats carrots"},
  {es:"ensalada", en:"salad", cat:"Sustantivos", ex:"una __ensalada__ mixta — a mixed salad"},
  {es:"sopa", en:"soup", cat:"Sustantivos", ex:"una __sopa__ caliente — a hot soup"},
  {es:"arroz", en:"rice", cat:"Sustantivos", ex:"paella de __arroz__ — rice paella"},
  {es:"hamburguesa", en:"hamburger", cat:"Sustantivos", ex:"una __hamburguesa__ con queso — a cheeseburger"},
  {es:"pizza", en:"pizza", cat:"Sustantivos", ex:"pedimos una __pizza__ — let's order a pizza"},
  {es:"tarta", en:"cake / pie", cat:"Sustantivos", ex:"una __tarta__ de cumpleaños — a birthday cake"},
  {es:"helado", en:"ice cream", cat:"Sustantivos", ex:"un __helado__ de chocolate — a chocolate ice cream"},
  {es:"galleta", en:"cookie / biscuit", cat:"Sustantivos", ex:"una __galleta__ para el café — a cookie for the coffee"},
  {es:"dulce", en:"sweet / candy", cat:"Sustantivos", ex:"me gusta el sabor __dulce__ — I like the sweet taste"},
  {es:"caramelo", en:"candy", cat:"Sustantivos", ex:"un __caramelo__ de menta — a mint candy"},
  {es:"chocolate", en:"chocolate", cat:"Sustantivos", ex:"una tableta de __chocolate__ — a chocolate bar"},
  {es:"refresco", en:"soda / soft drink", cat:"Sustantivos", ex:"un __refresco__ con hielo — a soda with ice"},
  {es:"hielo", en:"ice", cat:"Sustantivos", ex:"ponle __hielo__ a la bebida — put ice in the drink"},
  {es:"camisa", en:"shirt", cat:"Sustantivos", ex:"una __camisa__ de manga larga — a long-sleeve shirt"},
  {es:"falda", en:"skirt", cat:"Sustantivos", ex:"llevaba una __falda__ corta — she wore a short skirt"},
  {es:"chaqueta", en:"jacket", cat:"Sustantivos", ex:"hace frío, ponte la __chaqueta__ — it's cold, put on the jacket"},
  {es:"jersey", en:"sweater", cat:"Sustantivos", ex:"un __jersey__ de lana — a wool sweater"},
  {es:"sudadera", en:"sweatshirt / hoodie", cat:"Sustantivos", ex:"una __sudadera__ con capucha — a hoodie"},
  {es:"traje", en:"suit", cat:"Sustantivos", ex:"un __traje__ de chaqueta — a business suit"},
  {es:"corbata", en:"tie", cat:"Sustantivos", ex:"lleva traje y __corbata__ — he wears a suit and tie"},
  {es:"bufanda", en:"scarf", cat:"Sustantivos", ex:"ponte la __bufanda__ — put on your scarf"},
  {es:"guantes", en:"gloves", cat:"Sustantivos", ex:"no te olvides los __guantes__ — don't forget your gloves"},
  {es:"sombrero", en:"hat", cat:"Sustantivos", ex:"un __sombrero__ de paja — a straw hat"},
  {es:"gorra", en:"cap", cat:"Sustantivos", ex:"una __gorra__ deportiva — a sports cap"},
  {es:"calcetines", en:"socks", cat:"Sustantivos", ex:"__calcetines__ de algodón — cotton socks"},
  {es:"botas", en:"boots", cat:"Sustantivos", ex:"unas __botas__ de cuero — some leather boots"},
  {es:"zapatillas", en:"sneakers", cat:"Sustantivos", ex:"unas __zapatillas__ de deporte — some sports sneakers"},
  {es:"cinturón", en:"belt", cat:"Sustantivos", ex:"abróchate el __cinturón__ — buckle your belt"},
  {es:"anillo", en:"ring", cat:"Sustantivos", ex:"un __anillo__ de oro — a gold ring"},
  {es:"collar", en:"necklace", cat:"Sustantivos", ex:"un __collar__ de perlas — a pearl necklace"},
  {es:"nube", en:"cloud", cat:"Sustantivos", ex:"una __nube__ oscura — a dark cloud"},
  {es:"arena", en:"sand", cat:"Sustantivos", ex:"la __arena__ de la playa — the beach sand"},
  {es:"piedra", en:"stone", cat:"Sustantivos", ex:"tropezó con una __piedra__ — he tripped over a stone"},
  {es:"roca", en:"rock", cat:"Sustantivos", ex:"una __roca__ gigante — a giant rock"},
  {es:"lago", en:"lake", cat:"Sustantivos", ex:"bañarse en el __lago__ — to bathe in the lake"},
  {es:"selva", en:"jungle", cat:"Sustantivos", ex:"los animales de la __selva__ — the jungle animals"},
  {es:"hoja", en:"leaf / sheet", cat:"Sustantivos", ex:"una __hoja__ de papel — a sheet of paper"},
  {es:"hierba", en:"grass", cat:"Sustantivos", ex:"tumbarse en la __hierba__ — to lie down on the grass"},
  {es:"planta", en:"plant", cat:"Sustantivos", ex:"regar la __planta__ — to water the plant"},
  {es:"humo", en:"smoke", cat:"Sustantivos", ex:"huele a __humo__ — it smells like smoke"},
  {es:"calor", en:"heat", cat:"Sustantivos", ex:"hace mucho __calor__ — it's very hot"},
  {es:"tormenta", en:"storm", cat:"Sustantivos", ex:"viene una __tormenta__ — a storm is coming"},
  {es:"rayo", en:"lightning / ray", cat:"Sustantivos", ex:"un __rayo__ de luz — a ray of light"},
  {es:"mente", en:"mind", cat:"Sustantivos", ex:"tengo la __mente__ en blanco — my mind is blank"},
  {es:"memoria", en:"memory", cat:"Sustantivos", ex:"tengo mala __memoria__ — I have bad memory"},
  {es:"paz", en:"peace", cat:"Sustantivos", ex:"queremos la __paz__ — we want peace"},
  {es:"guerra", en:"war", cat:"Sustantivos", ex:"la __guerra__ terminó — the war ended"},
  {es:"amor", en:"love", cat:"Sustantivos", ex:"el __amor__ de mi vida — the love of my life"},
  {es:"odio", en:"hate", cat:"Sustantivos", ex:"el __odio__ no es bueno — hate is not good"},
  {es:"alegría", en:"joy", cat:"Sustantivos", ex:"llorar de __alegría__ — to cry of joy"},
  {es:"tristeza", en:"sadness", cat:"Sustantivos", ex:"sentir una gran __tristeza__ — to feel a great sadness"},
  {es:"miedo", en:"fear", cat:"Sustantivos", ex:"tengo __miedo__ a la oscuridad — I'm afraid of the dark"},
  {es:"sorpresa", en:"surprise", cat:"Sustantivos", ex:"fue una gran __sorpresa__ — it was a big surprise"},
  {es:"culpa", en:"fault / guilt", cat:"Sustantivos", ex:"fue mi __culpa__ — it was my fault"},
  {es:"dolor", en:"pain", cat:"Sustantivos", ex:"un __dolor__ de cabeza — a headache"},
  {es:"enfermedad", en:"disease", cat:"Sustantivos", ex:"es una __enfermedad__ rara — it's a rare disease"},
  {es:"salud", en:"health", cat:"Sustantivos", ex:"¡__salud__! (al brindar) — cheers! (when toasting)"},
  {es:"belleza", en:"beauty", cat:"Sustantivos", ex:"la __belleza__ de la naturaleza — the beauty of nature"},
  {es:"sonido", en:"sound", cat:"Sustantivos", ex:"un __sonido__ extraño — a strange sound"},
  {es:"silencio", en:"silence", cat:"Sustantivos", ex:"¡guardad __silencio__! — keep silent!"},
  {es:"voz", en:"voice", cat:"Sustantivos", ex:"tiene una __voz__ bonita — he has a nice voice"},
  {es:"ruido", en:"noise", cat:"Sustantivos", ex:"hay mucho __ruido__ aquí — there's a lot of noise here"},
  {es:"sombra", en:"shadow / shade", cat:"Sustantivos", ex:"vamos a la __sombra__ — let's go to the shade"},
  {es:"color", en:"color", cat:"Sustantivos", ex:"¿cuál es tu __color__ favorito? — what is your favorite color?"},
  {es:"tamaño", en:"size", cat:"Sustantivos", ex:"¿qué __tamaño__ necesitas? — what size do you need?"},
  {es:"número", en:"number", cat:"Sustantivos", ex:"mi __número__ de teléfono — my phone number"},
  {es:"letra", en:"letter (alphabet)", cat:"Sustantivos", ex:"la primera __letra__ — the first letter"},
  {es:"oración", en:"sentence / prayer", cat:"Sustantivos", ex:"escribe una __oración__ — write a sentence"},
  {es:"texto", en:"text", cat:"Sustantivos", ex:"lee el __texto__ — read the text"},
  {es:"mensaje", en:"message", cat:"Sustantivos", ex:"déjame un __mensaje__ — leave me a message"},
  {es:"nota", en:"note / grade", cat:"Sustantivos", ex:"toma __nota__ de esto — take note of this"},
  {es:"página", en:"page", cat:"Sustantivos", ex:"abre la __página__ diez — open page ten"},
  {es:"revista", en:"magazine", cat:"Sustantivos", ex:"leer una __revista__ — to read a magazine"},
  {es:"periódico", en:"newspaper", cat:"Sustantivos", ex:"comprar el __periódico__ — to buy the newspaper"},
  {es:"noticia", en:"news", cat:"Sustantivos", ex:"tengo una buena __noticia__ — I have good news"},
  {es:"información", en:"information", cat:"Sustantivos", ex:"necesito más __información__ — I need more information"},
  {es:"secreto", en:"secret", cat:"Sustantivos", ex:"es un __secreto__ — it's a secret"},
  {es:"regla", en:"rule / ruler", cat:"Sustantivos", ex:"es una __regla__ estricta — it's a strict rule"},
  {es:"ley", en:"law", cat:"Sustantivos", ex:"cumplir la __ley__ — to follow the law"},
  {es:"gobierno", en:"government", cat:"Sustantivos", ex:"el __gobierno__ de España — the government of Spain"},
  {es:"dios", en:"god", cat:"Sustantivos", ex:"¡por __dios__! — for god's sake!"},
  {es:"religión", en:"religion", cat:"Sustantivos", ex:"la __religión__ católica — the catholic religion"},
  {es:"ciencia", en:"science", cat:"Sustantivos", ex:"la clase de __ciencia__ — the science class"},
  {es:"baile", en:"dance", cat:"Sustantivos", ex:"vamos al __baile__ — let's go to the dance"},
  {es:"bailar", en:"to dance", cat:"Verbos", ex:"me gusta __bailar__ — I like dancing"},
  {es:"nadar", en:"to swim", cat:"Verbos", ex:"sabe __nadar__ muy bien — he knows how to swim very well"},
  {es:"caminar", en:"to walk", cat:"Verbos", ex:"vamos a __caminar__ por la playa — let's walk on the beach"},
  {es:"pasear", en:"to take a walk", cat:"Verbos", ex:"sacar a __pasear__ al perro — to take the dog for a walk"},
  {es:"viajar", en:"to travel", cat:"Verbos", ex:"__viajar__ por Europa — to travel around Europe"},
  {es:"crecer", en:"to grow", cat:"Verbos", ex:"el niño va a __crecer__ mucho — the boy is going to grow a lot"},
  {es:"luchar", en:"to fight / struggle", cat:"Verbos", ex:"tienes que __luchar__ por tus sueños — you have to fight for your dreams"},
  {es:"pelear", en:"to fight", cat:"Verbos", ex:"no te vuelvas a __pelear__ — don't fight again"},
  {es:"golpear", en:"to hit", cat:"Verbos", ex:"no le puedes __golpear__ — you can't hit him"},
  {es:"cerrar", en:"to close", cat:"Verbos", ex:"voy a __cerrar__ la ventana — I will close the window"},
  {es:"ensuciar", en:"to get dirty", cat:"Verbos", ex:"cuidado de no __ensuciar__ el sofá — careful not to dirty the sofa"},
  {es:"lavar", en:"to wash", cat:"Verbos", ex:"tengo que __lavar__ la ropa — I have to wash the clothes"},
  {es:"secar", en:"to dry", cat:"Verbos", ex:"tienes que __secar__ los platos — you have to dry the plates"},
  {es:"planchar", en:"to iron", cat:"Verbos", ex:"hoy toca __planchar__ — today it's time to iron"},
  {es:"barrer", en:"to sweep", cat:"Verbos", ex:"voy a __barrer__ el suelo — I'm going to sweep the floor"},
  {es:"preparar", en:"to prepare", cat:"Verbos", ex:"voy a __preparar__ la cena — I will prepare dinner"},
  {es:"tragar", en:"to swallow", cat:"Verbos", ex:"me cuesta __tragar__ — it's hard for me to swallow"},
  {es:"masticar", en:"to chew", cat:"Verbos", ex:"tienes que __masticar__ bien — you have to chew well"},
  {es:"oler", en:"to smell", cat:"Verbos", ex:"puedo __oler__ el café — I can smell the coffee"},
  {es:"saborear", en:"to savor / taste", cat:"Verbos", ex:"__saborear__ un buen vino — to savor a good wine"},
  {es:"observar", en:"to observe", cat:"Verbos", ex:"me gusta __observar__ a la gente — I like observing people"},
  {es:"sonreír", en:"to smile", cat:"Verbos", ex:"ella volvió a __sonreír__ — she smiled again"},
  {es:"gritar", en:"to shout", cat:"Verbos", ex:"no hace falta __gritar__ — there's no need to shout"},
  {es:"susurrar", en:"to whisper", cat:"Verbos", ex:"empezó a __susurrar__ — he started to whisper"},
  {es:"responder", en:"to respond", cat:"Verbos", ex:"tienes que __responder__ a mi email — you have to respond to my email"},
  {es:"contestar", en:"to answer", cat:"Verbos", ex:"alguien tiene que __contestar__ — someone has to answer"},
  {es:"aprender", en:"to learn", cat:"Verbos", ex:"quiero __aprender__ español — I want to learn Spanish"},
  {es:"calcular", en:"to calculate", cat:"Verbos", ex:"vamos a __calcular__ los gastos — let's calculate the expenses"},
  {es:"sumar", en:"to add", cat:"Verbos", ex:"tienes que __sumar__ los números — you have to add the numbers"},
  {es:"restar", en:"to subtract", cat:"Verbos", ex:"ahora tienes que __restar__ esto — now you have to subtract this"},
  {es:"cobrar", en:"to charge (money)", cat:"Verbos", ex:"¿cuánto me vas a __cobrar__? — how much are you going to charge me?"},
  {es:"costar", en:"to cost", cat:"Verbos", ex:"esto puede __costar__ mucho — this can cost a lot"},
  {es:"ahorrar", en:"to save (money/time)", cat:"Verbos", ex:"quiero __ahorrar__ para un coche — I want to save for a car"},
  {es:"esconder", en:"to hide", cat:"Verbos", ex:"te voy a __esconder__ un regalo — I will hide a gift for you"},
  {es:"coger", en:"to take / grab / catch", cat:"Verbos", ex:"vamos a __coger__ el tren — let's catch the train"},
  {es:"guardar", en:"to save / keep", cat:"Verbos", ex:"voy a __guardar__ el documento — I will save the document"},
  {es:"triste", en:"sad", cat:"Adjetivos", ex:"hoy me siento __triste__ — today I feel sad"},
  {es:"enfadado/enfadada", en:"angry", cat:"Adjetivos", ex:"está muy __enfadado__ conmigo — he is very angry with me"},
  {es:"enojado/enojada", en:"angry", cat:"Adjetivos", ex:"no te pongas __enojado__ — don't get angry"},
  {es:"enfermo/enferma", en:"sick", cat:"Adjetivos", ex:"el niño está __enfermo__ — the boy is sick"},
  {es:"sano/sana", en:"healthy", cat:"Adjetivos", ex:"comer de forma __sana__ — to eat healthy"},
  {es:"loco/loca", en:"crazy", cat:"Adjetivos", ex:"¡estás __loco__! — you are crazy!"},
  {es:"cuerdo/cuerda", en:"sane", cat:"Adjetivos", ex:"no parece estar muy __cuerdo__ — he doesn't seem very sane"},
  {es:"inteligente", en:"intelligent", cat:"Adjetivos", ex:"es una chica muy __inteligente__ — she is a very intelligent girl"},
  {es:"tonto/tonta", en:"silly / dumb", cat:"Adjetivos", ex:"no seas __tonto__ — don't be silly"},
  {es:"estúpido/estúpida", en:"stupid", cat:"Adjetivos", ex:"fue un error __estúpido__ — it was a stupid mistake"},
  {es:"listo/lista", en:"smart / ready", cat:"Adjetivos", ex:"ya estoy __listo__ — I'm ready now"},
  {es:"amable", en:"kind", cat:"Adjetivos", ex:"él es muy __amable__ — he is very kind"},
  {es:"simpático/simpática", en:"nice / friendly", cat:"Adjetivos", ex:"el camarero fue muy __simpático__ — the waiter was very friendly"},
  {es:"antipático/antipática", en:"unfriendly", cat:"Adjetivos", ex:"me pareció muy __antipático__ — I found him very unfriendly"},
  {es:"valiente", en:"brave", cat:"Adjetivos", ex:"un soldado __valiente__ — a brave soldier"},
  {es:"cobarde", en:"coward", cat:"Adjetivos", ex:"no seas __cobarde__ — don't be a coward"},
  {es:"tímido/tímida", en:"shy", cat:"Adjetivos", ex:"es un poco __tímido__ — he is a bit shy"},
  {es:"divertido/divertida", en:"fun", cat:"Adjetivos", ex:"fue una fiesta muy __divertida__ — it was a very fun party"},
  {es:"aburrido/aburrida", en:"boring / bored", cat:"Adjetivos", ex:"estoy muy __aburrido__ — I am very bored"},
  {es:"interesante", en:"interesting", cat:"Adjetivos", ex:"un libro muy __interesante__ — a very interesting book"},
  {es:"extraño/extraña", en:"strange", cat:"Adjetivos", ex:"hace un ruido __extraño__ — it makes a strange noise"},
  {es:"raro/rara", en:"weird / rare", cat:"Adjetivos", ex:"eso es muy __raro__ — that's very weird"},
  {es:"común", en:"common", cat:"Adjetivos", ex:"es un problema muy __común__ — it's a very common problem"},
  {es:"normal", en:"normal", cat:"Adjetivos", ex:"es una reacción __normal__ — it's a normal reaction"},
  {es:"natural", en:"natural", cat:"Adjetivos", ex:"un sabor muy __natural__ — a very natural flavor"},
  {es:"artificial", en:"artificial", cat:"Adjetivos", ex:"luz __artificial__ — artificial light"},
  {es:"duro/dura", en:"hard", cat:"Adjetivos", ex:"el pan está __duro__ — the bread is hard"},
  {es:"blando/blanda", en:"soft", cat:"Adjetivos", ex:"una cama muy __blanda__ — a very soft bed"},
  {es:"suave", en:"soft / smooth", cat:"Adjetivos", ex:"su piel es muy __suave__ — her skin is very soft"},
  {es:"áspero/áspera", en:"rough", cat:"Adjetivos", ex:"una superficie __áspera__ — a rough surface"},
  {es:"pesado/pesada", en:"heavy", cat:"Adjetivos", ex:"esta caja es muy __pesada__ — this box is very heavy"},
  {es:"ligero/ligera", en:"light (weight)", cat:"Adjetivos", ex:"un equipaje __ligero__ — light luggage"},
  {es:"adulto/adulta", en:"adult", cat:"Sustantivos", ex:"ya soy un __adulto__ — I am an adult now"},
  {es:"enorme", en:"enormous", cat:"Adjetivos", ex:"un problema __enorme__ — an enormous problem"},
  {es:"diminuto/diminuta", en:"tiny", cat:"Adjetivos", ex:"un insecto __diminuto__ — a tiny insect"},
  {es:"profundo/profunda", en:"deep", cat:"Adjetivos", ex:"el río es muy __profundo__ — the river is very deep"},
  {es:"brillante", en:"bright / brilliant", cat:"Adjetivos", ex:"una idea __brillante__ — a brilliant idea"},
  {es:"opaco/opaca", en:"opaque / dull", cat:"Adjetivos", ex:"un cristal __opaco__ — an opaque glass"},
  {es:"seco/seca", en:"dry", cat:"Adjetivos", ex:"tengo la ropa __seca__ — my clothes are dry"},
  {es:"mojado/mojada", en:"wet", cat:"Adjetivos", ex:"cuidado, el suelo está __mojado__ — careful, the floor is wet"},
  {es:"tibio/tibia", en:"lukewarm / warm", cat:"Adjetivos", ex:"el agua está __tibia__ — the water is lukewarm"},
  {es:"hermoso/hermosa", en:"beautiful", cat:"Adjetivos", ex:"un __hermoso__ paisaje — a beautiful landscape"},
  {es:"bello/bella", en:"beautiful", cat:"Adjetivos", ex:"una __bella__ historia — a beautiful story"},
  {es:"guapo/guapa", en:"handsome / pretty", cat:"Adjetivos", ex:"¡qué __guapa__ estás hoy! — how pretty you look today!"},
  {es:"lindo/linda", en:"cute / nice", cat:"Adjetivos", ex:"un perrito muy __lindo__ — a very cute doggie"},
  {es:"precioso/preciosa", en:"gorgeous / precious", cat:"Adjetivos", ex:"un vestido __precioso__ — a gorgeous dress"},
  {es:"perfecto/perfecta", en:"perfect", cat:"Adjetivos", ex:"ha sido un día __perfecto__ — it has been a perfect day"},
  {es:"excelente", en:"excellent", cat:"Adjetivos", ex:"un trabajo __excelente__ — an excellent job"},
  {es:"horrible", en:"horrible", cat:"Adjetivos", ex:"huele __horrible__ — it smells horrible"},
  {es:"terrible", en:"terrible", cat:"Adjetivos", ex:"fue una experiencia __terrible__ — it was a terrible experience"},
  {es:"maravilloso/maravillosa", en:"wonderful", cat:"Adjetivos", ex:"un viaje __maravilloso__ — a wonderful trip"},
  {es:"útil", en:"useful", cat:"Adjetivos", ex:"esto me será muy __útil__ — this will be very useful to me"},
  {es:"inútil", en:"useless", cat:"Adjetivos", ex:"es totalmente __inútil__ — it's totally useless"},
  {es:"anterior", en:"previous", cat:"Adjetivos", ex:"la página __anterior__ — the previous page"},
  {es:"acompañado/acompañada", en:"accompanied", cat:"Adjetivos", ex:"mejor solo que mal __acompañado__ — better alone than in bad company"},
  {es:"junto/junta", en:"together", cat:"Adjetivos", ex:"vamos a hacerlo __juntos__ — let's do it together"},
  {es:"separado/separada", en:"separate", cat:"Adjetivos", ex:"quiero las cuentas __separadas__ — I want separate bills"},
  {es:"diferente", en:"different", cat:"Adjetivos", ex:"somos muy __diferentes__ — we are very different"},
  {es:"propio/propia", en:"own", cat:"Adjetivos", ex:"tengo mi __propio__ negocio — I have my own business"},
  {es:"ajeno/ajena", en:"someone else's / foreign", cat:"Adjetivos", ex:"no te metas en lo __ajeno__ — don't meddle in what isn't yours"},
  {es:"acá", en:"here (movement)", cat:"Gramática", ex:"ven para __acá__ — come over here"},
  {es:"allá", en:"there (movement)", cat:"Gramática", ex:"vamos para __allá__ — let's go over there"},
  {es:"encima", en:"on top", cat:"Gramática", ex:"está __encima__ de la mesa — it's on top of the table"},
  {es:"debajo", en:"underneath", cat:"Gramática", ex:"hay un monstruo __debajo__ de la cama — there's a monster underneath the bed"},
  {es:"enfrente", en:"opposite / in front", cat:"Gramática", ex:"vivo en la casa de __enfrente__ — I live in the house opposite"},
  {es:"al lado", en:"next to", cat:"Gramática", ex:"siéntate __al lado__ mío — sit next to me"},
  {es:"después", en:"after", cat:"Gramática", ex:"vamos __después__ de comer — let's go after eating"},
  {es:"jamás", en:"never", cat:"Gramática", ex:"yo __jamás__ haría eso — I would never do that"},
  {es:"aún", en:"still / yet", cat:"Gramática", ex:"__aún__ no lo he hecho — I still haven't done it"},
  {es:"apenas", en:"barely / hardly", cat:"Gramática", ex:"__apenas__ tengo dinero — I barely have money"},
  {es:"tan", en:"so (with adjectives)", cat:"Gramática", ex:"eres __tan__ alto como yo — you are as tall as me"},
  {es:"mal", en:"badly / bad", cat:"Gramática", ex:"me siento __mal__ — I feel bad"},
  {es:"quizá", en:"maybe / perhaps", cat:"Gramática", ex:"__quizá__ llueva mañana — maybe it will rain tomorrow"},
  {es:"tal vez", en:"maybe", cat:"Gramática", ex:"__tal vez__ sea verdad — maybe it is true"},
  {es:"a lo mejor", en:"maybe / probably", cat:"Gramática", ex:"__a lo mejor__ voy más tarde — maybe I'll go later"},
  {es:"por supuesto", en:"of course", cat:"Frases", ex:"__por supuesto__ que sí — of course"},
  {es:"ni", en:"nor / neither", cat:"Gramática", ex:"no quiero esto __ni__ aquello — I don't want this nor that"},
  {es:"porque", en:"because", cat:"Gramática", ex:"no fui __porque__ estaba cansado — I didn't go because I was tired"},
  {es:"pues", en:"well / then", cat:"Gramática", ex:"__pues__ no sé qué decir — well, I don't know what to say"},
  {es:"ya que", en:"since / seeing that", cat:"Gramática", ex:"__ya que__ estás aquí, ayúdame — since you are here, help me"},
  {es:"mas", en:"but (literary)", cat:"Gramática", ex:"quise hablar, __mas__ no pude — I wanted to speak, but couldn't"},
  {es:"sino", en:"but rather", cat:"Gramática", ex:"no es azul, __sino__ verde — it's not blue, but rather green"},
  {es:"claro (adv)", en:"of course", cat:"Gramática", ex:"__claro__, te entiendo — of course, I understand you"}
];
